include:
  file: bookworm-minbase.yaml

device:
  hostname: toquehub
  layer: rpi5

image:
  name: toquehub-pi64
  root_part_size: 600%

locale:
  default: fr_FR.UTF-8
  keyboard_keymap: fr
  keyboard_layout: French
  timezone: Europe/Paris

layer:
  docker: docker-debian-bookworm
  app: toquehub-appliance
