ALTER TABLE "haccp_products" ADD COLUMN "clientId" TEXT, ADD COLUMN "clientUpdatedAt" TIMESTAMP(3), ADD COLUMN "deletedAt" TIMESTAMP(3), ADD COLUMN "syncVersion" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "haccp_temperature_equipment" ADD COLUMN "clientId" TEXT, ADD COLUMN "clientUpdatedAt" TIMESTAMP(3), ADD COLUMN "deletedAt" TIMESTAMP(3), ADD COLUMN "syncVersion" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "haccp_temperature_readings" ADD COLUMN "clientId" TEXT, ADD COLUMN "clientUpdatedAt" TIMESTAMP(3), ADD COLUMN "deletedAt" TIMESTAMP(3), ADD COLUMN "syncVersion" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "haccp_receptions" ADD COLUMN "clientId" TEXT, ADD COLUMN "clientUpdatedAt" TIMESTAMP(3), ADD COLUMN "deletedAt" TIMESTAMP(3), ADD COLUMN "syncVersion" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "haccp_traceability" ADD COLUMN "clientId" TEXT, ADD COLUMN "clientUpdatedAt" TIMESTAMP(3), ADD COLUMN "deletedAt" TIMESTAMP(3), ADD COLUMN "syncVersion" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "haccp_process_equipment" ADD COLUMN "clientId" TEXT, ADD COLUMN "clientUpdatedAt" TIMESTAMP(3), ADD COLUMN "deletedAt" TIMESTAMP(3), ADD COLUMN "syncVersion" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "haccp_process_sessions" ADD COLUMN "clientId" TEXT, ADD COLUMN "clientUpdatedAt" TIMESTAMP(3), ADD COLUMN "deletedAt" TIMESTAMP(3), ADD COLUMN "syncVersion" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "haccp_oil_equipment" ADD COLUMN "clientId" TEXT, ADD COLUMN "clientUpdatedAt" TIMESTAMP(3), ADD COLUMN "deletedAt" TIMESTAMP(3), ADD COLUMN "syncVersion" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "haccp_oil_sessions" ADD COLUMN "clientId" TEXT, ADD COLUMN "clientUpdatedAt" TIMESTAMP(3), ADD COLUMN "deletedAt" TIMESTAMP(3), ADD COLUMN "syncVersion" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "haccp_cleaning_zones" ADD COLUMN "clientId" TEXT, ADD COLUMN "clientUpdatedAt" TIMESTAMP(3), ADD COLUMN "deletedAt" TIMESTAMP(3), ADD COLUMN "syncVersion" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "haccp_cleaning_surfaces" ADD COLUMN "clientId" TEXT, ADD COLUMN "clientUpdatedAt" TIMESTAMP(3), ADD COLUMN "deletedAt" TIMESTAMP(3), ADD COLUMN "syncVersion" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "haccp_cleaning_sessions" ADD COLUMN "clientId" TEXT, ADD COLUMN "clientUpdatedAt" TIMESTAMP(3), ADD COLUMN "deletedAt" TIMESTAMP(3), ADD COLUMN "syncVersion" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "haccp_cleaned_surfaces" ADD COLUMN "clientId" TEXT, ADD COLUMN "clientUpdatedAt" TIMESTAMP(3), ADD COLUMN "deletedAt" TIMESTAMP(3), ADD COLUMN "syncVersion" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "haccp_production_sessions" ADD COLUMN "clientId" TEXT, ADD COLUMN "clientUpdatedAt" TIMESTAMP(3), ADD COLUMN "deletedAt" TIMESTAMP(3), ADD COLUMN "syncVersion" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "haccp_daily_reports" ADD COLUMN "clientId" TEXT, ADD COLUMN "clientUpdatedAt" TIMESTAMP(3), ADD COLUMN "deletedAt" TIMESTAMP(3), ADD COLUMN "syncVersion" INTEGER NOT NULL DEFAULT 1;

CREATE UNIQUE INDEX "haccp_products_organizationId_clientId_key" ON "haccp_products"("organizationId", "clientId") WHERE "clientId" IS NOT NULL;
CREATE UNIQUE INDEX "haccp_temperature_equipment_organizationId_clientId_key" ON "haccp_temperature_equipment"("organizationId", "clientId") WHERE "clientId" IS NOT NULL;
CREATE UNIQUE INDEX "haccp_temperature_readings_organizationId_clientId_key" ON "haccp_temperature_readings"("organizationId", "clientId") WHERE "clientId" IS NOT NULL;
CREATE UNIQUE INDEX "haccp_receptions_organizationId_clientId_key" ON "haccp_receptions"("organizationId", "clientId") WHERE "clientId" IS NOT NULL;
CREATE UNIQUE INDEX "haccp_traceability_organizationId_clientId_key" ON "haccp_traceability"("organizationId", "clientId") WHERE "clientId" IS NOT NULL;
CREATE UNIQUE INDEX "haccp_process_equipment_organizationId_clientId_key" ON "haccp_process_equipment"("organizationId", "clientId") WHERE "clientId" IS NOT NULL;
CREATE UNIQUE INDEX "haccp_process_sessions_organizationId_clientId_key" ON "haccp_process_sessions"("organizationId", "clientId") WHERE "clientId" IS NOT NULL;
CREATE UNIQUE INDEX "haccp_oil_equipment_organizationId_clientId_key" ON "haccp_oil_equipment"("organizationId", "clientId") WHERE "clientId" IS NOT NULL;
CREATE UNIQUE INDEX "haccp_oil_sessions_organizationId_clientId_key" ON "haccp_oil_sessions"("organizationId", "clientId") WHERE "clientId" IS NOT NULL;
CREATE UNIQUE INDEX "haccp_cleaning_zones_organizationId_clientId_key" ON "haccp_cleaning_zones"("organizationId", "clientId") WHERE "clientId" IS NOT NULL;
CREATE UNIQUE INDEX "haccp_cleaning_surfaces_organizationId_clientId_key" ON "haccp_cleaning_surfaces"("organizationId", "clientId") WHERE "clientId" IS NOT NULL;
CREATE UNIQUE INDEX "haccp_cleaning_sessions_organizationId_clientId_key" ON "haccp_cleaning_sessions"("organizationId", "clientId") WHERE "clientId" IS NOT NULL;
CREATE UNIQUE INDEX "haccp_cleaned_surfaces_organizationId_clientId_key" ON "haccp_cleaned_surfaces"("organizationId", "clientId") WHERE "clientId" IS NOT NULL;
CREATE UNIQUE INDEX "haccp_production_sessions_organizationId_clientId_key" ON "haccp_production_sessions"("organizationId", "clientId") WHERE "clientId" IS NOT NULL;
CREATE UNIQUE INDEX "haccp_daily_reports_organizationId_clientId_key" ON "haccp_daily_reports"("organizationId", "clientId") WHERE "clientId" IS NOT NULL;
