import { Injectable, NotFoundException, OnModuleDestroy, OnModuleInit } from '@nestjs/common';
import { HaccpAssistantDraftStatus, HaccpAssistantMessageRole } from '@prisma/client';
import { HaccpService } from '../haccp/haccp.service';
import { HaccpSensorsService } from '../haccp/iot/haccp-sensors.service';
import { PrismaService } from '../prisma/prisma.service';
import { HaccpAgentHarnessService } from './haccp-agent-harness.service';
type Actor = { id: string; role: string }; const expiry = () => new Date(Date.now() + 30 * 86400000);
@Injectable()
export class HaccpAssistantService implements OnModuleInit, OnModuleDestroy {
  private timer?: NodeJS.Timeout;
  constructor(private readonly prisma: PrismaService, private readonly haccp: HaccpService, private readonly sensors: HaccpSensorsService, private readonly harness: HaccpAgentHarnessService) {}
  onModuleInit() { this.timer = setInterval(() => void this.expire(), 86400000); this.timer.unref?.(); }
  onModuleDestroy() { if (this.timer) clearInterval(this.timer); }
  async create(org: string, actor: Actor) { return (this.prisma as any).haccpAssistantConversation.create({ data: { organizationId: org, userId: actor.id, state: {}, summary: {}, expiresAt: expiry() } }); }
  async conversation(org: string, actor: Actor, id: string) { const c = await (this.prisma as any).haccpAssistantConversation.findFirst({ where: { id, organizationId: org, userId: actor.id }, include: { messages: { orderBy: { createdAt: 'asc' } } } }); if (!c) throw new NotFoundException('Conversation HACCP introuvable'); return c; }
  async draft(org: string, actor: Actor, id: string) { const d = await (this.prisma as any).haccpAssistantDraft.findFirst({ where: { id, organizationId: org, conversation: { userId: actor.id } } }); if (!d) throw new NotFoundException('Brouillon HACCP introuvable'); return d; }
  async message(org: string, actor: Actor, id: string, content: string) {
    const c = await this.conversation(org, actor, id); await (this.prisma as any).haccpAssistantMessage.create({ data: { conversationId: id, role: HaccpAssistantMessageRole.USER, content } });
    const context = await this.context(org); const call = await this.harness.decide(org, content, c.state || {}, context); const result: any = await this.execute(org, id, call.tool, call.args || {});
    const state = { ...(c.state || {}), ...(result.statePatch || {}), lastTool: call.tool }; await (this.prisma as any).$transaction([(this.prisma as any).haccpAssistantMessage.create({ data: { conversationId: id, role: HaccpAssistantMessageRole.ASSISTANT, content: result.assistantMessage, metadata: { draftId: result.draftId || null, choices: result.choices || [], tool: call.tool, needsReview: !!result.needsReview } } }), (this.prisma as any).haccpAssistantConversation.update({ where: { id }, data: { state, summary: { lastTool: call.tool }, expiresAt: expiry() } })]); return { ...result, state, confidence: call.confidence };
  }
  async apply(org: string, actor: Actor, id: string) { const d: any = await this.draft(org, actor, id); if (d.status !== HaccpAssistantDraftStatus.PENDING_REVIEW) throw new Error('Brouillon déjà traité'); const p: any = d.payload; let result: any; if (d.kind === 'temperature') result = await this.haccp.createTemperatureReading(org, actor, p); else if (d.kind === 'cleaning_start') result = await this.haccp.startCleaningSession(org, actor); else if (d.kind === 'cleaning_mark') result = await this.haccp.markSurfaceCleaned(org, actor, p); else if (d.kind === 'cleaning_complete') result = await this.haccp.completeCleaningSession(org, p); else throw new Error('Brouillon HACCP non supporté'); await (this.prisma as any).haccpAssistantDraft.update({ where: { id }, data: { status: HaccpAssistantDraftStatus.APPLIED } }); return result;
  }
  private async execute(org: string, conversationId: string, tool: string, args: any) {
    if (tool === 'get_haccp_dashboard') { const x: any = await this.haccp.dashboard(org); const d = x.data; return { assistantMessage: `Score HACCP du jour : ${d.score}/100 (${d.grade}). ${d.alerts.length ? `${d.alerts.length} alerte(s) à traiter.` : 'Aucune alerte ouverte.'}`, data: d }; }
    if (tool === 'list_haccp_alerts') { const [dash, sensor] = await Promise.all([this.haccp.dashboard(org), this.sensors.temperatureAlerts(org)]); const alerts = [...((dash as any).data.alerts || []), ...(sensor.alerts || [])]; return { assistantMessage: alerts.length ? alerts.map((a: any) => `• ${a.message || a.title}`).join('\n') : 'Aucune alerte HACCP ouverte.', data: alerts }; }
    if (tool === 'list_temperature_equipment' || tool === 'get_temperature_status') { const [equipment, readings] = await Promise.all([this.haccp.listTemperatureEquipment(org), this.haccp.listTemperatureReadings(org)]); const rows = (equipment.data || []).map((e: any) => ({ ...e, reading: (readings.data || []).find((r: any) => r.equipmentId === e._id) })); return { assistantMessage: rows.length ? rows.map((r: any) => `• ${r.name} : ${r.reading?.temperature ?? 'aucun relevé'}${r.reading ? '°C' : ''}`).join('\n') : 'Aucun équipement température actif.', data: rows, choices: rows.map((r: any) => ({ type: 'haccp_equipment', label: r.name, value: r._id })) }; }
    if (tool === 'get_cleaning_status') { const [active, surfaces] = await Promise.all([this.haccp.getActiveCleaningSession(org), this.haccp.todayCleaningSurfaces(org)]); const a: any = active.data; const due: any[] = surfaces.data || []; return { assistantMessage: a ? `Nettoyage en cours : ${a.completedSurfaces}/${a.totalSurfaces} surfaces validées.` : `${due.length} surface(s) prévue(s) au nettoyage aujourd’hui.`, data: { active: a, due } }; }
    if (tool === 'prepare_temperature_reading' || tool === 'prepare_corrective_control') { const equipment: any = await this.haccp.listTemperatureEquipment(org); const items = equipment.data || []; const equipmentName = String(args.equipmentName || '').trim().toLowerCase(); const selected = items.find((x: any) => x._id === args.equipmentId) || (equipmentName ? items.find((x: any) => x.name?.toLowerCase().includes(equipmentName) || equipmentName.includes(x.name?.toLowerCase())) : undefined); if (!selected) return { assistantMessage: 'Pour quel équipement souhaitez-vous enregistrer le relevé ?', choices: items.map((x: any) => ({ type: 'haccp_equipment', label: x.name, value: x._id })), statePatch: { pendingIntent: 'temperature' } }; if (!Number.isFinite(Number(args.temperature))) return { assistantMessage: `Quelle température avez-vous relevée pour ${selected.name} ?`, statePatch: { pendingIntent: 'temperature', activeEquipmentId: selected._id } }; return this.makeDraft(org, conversationId, 'temperature', { equipmentId: selected._id, temperature: Number(args.temperature), date: new Date().toISOString(), notes: args.notes || 'Saisie proposée par Kokki HACCP' }, `Relevé proposé : ${selected.name} — ${Number(args.temperature)} °C.`); }
    if (tool === 'prepare_cleaning_session') { const action = args.action || 'start'; if (action === 'mark') { const due: any = await this.haccp.todayCleaningSurfaces(org); const surfaces = due.data || []; const selected = surfaces.find((x: any) => x.surfaceId === args.surfaceId); if (!selected) return { assistantMessage: 'Quelle surface avez-vous nettoyée ?', choices: surfaces.map((x: any) => ({ type: 'haccp_surface', label: `${x.zoneName} — ${x.surfaceName}`, value: x.surfaceId, payload: { zoneId: x.zoneId, zoneName: x.zoneName } })), statePatch: { pendingIntent: 'cleaning_mark' } }; return this.makeDraft(org, conversationId, 'cleaning_mark', { surfaceId: selected.surfaceId, surfaceName: selected.surfaceName, zoneId: selected.zoneId, zoneName: selected.zoneName, notes: args.notes || 'Saisie proposée par Kokki HACCP' }, `Nettoyage proposé : ${selected.zoneName} — ${selected.surfaceName}.`); } return this.makeDraft(org, conversationId, action === 'complete' ? 'cleaning_complete' : 'cleaning_start', { notes: args.notes || 'Saisie proposée par Kokki HACCP' }, action === 'complete' ? 'Clôture du nettoyage proposée.' : 'Démarrage du nettoyage proposé.'); }
    return { assistantMessage: args.message || 'Je peux vérifier les alertes, températures et nettoyages HACCP.' };
  }
  private async makeDraft(org: string, conversationId: string, kind: string, payload: any, message: string) { const d = await (this.prisma as any).haccpAssistantDraft.create({ data: { organizationId: org, conversationId, kind, payload, expiresAt: expiry() } }); return { assistantMessage: `${message}\n\nVérifiez puis validez ce brouillon.`, draftId: d.id, draft: d, needsReview: true, choices: [{ type: 'haccp_draft_review', label: 'Vérifier & appliquer', value: d.id }] }; }
  private async context(org: string) { const [dashboard, equipment, alerts] = await Promise.all([this.haccp.dashboard(org), this.haccp.listTemperatureEquipment(org), this.sensors.temperatureAlerts(org)]); return { dashboard: (dashboard as any).data, equipment: equipment.data || [], sensorAlerts: alerts.alerts || [] }; }
  private async expire() { const now = new Date(); await (this.prisma as any).haccpAssistantDraft.updateMany({ where: { status: HaccpAssistantDraftStatus.PENDING_REVIEW, expiresAt: { lt: now } }, data: { status: HaccpAssistantDraftStatus.EXPIRED } }); await (this.prisma as any).haccpAssistantConversation.deleteMany({ where: { expiresAt: { lt: now } } }); }
}
