import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { AuditAction, Prisma, TechnicalSheetExportFormat, TechnicalSheetHistoryAction, TechnicalSheetStatus } from '@prisma/client';
import { PrismaService } from '../prisma/prisma.service';
import { DuplicateTechnicalSheetDto, ProductionSimulationDto, TechnicalSheetListQueryDto, UpsertAllergenDto, UpsertRecipeCategoryDto, UpsertTechnicalSheetDto } from './dto/technical-sheets.dto';

type Actor = { id: string; role: string };
type Tx = Prisma.TransactionClient;

const DEFAULT_CATEGORIES = ['Entrées', 'Plats', 'Desserts', 'Sauces', 'Accompagnements', 'Petit-déjeuner', 'Pâtisserie', 'Boulangerie', 'Boissons'];
const DEFAULT_ALLERGENS = ['Gluten', 'Crustacés', 'Œufs', 'Poissons', 'Arachides', 'Soja', 'Lait', 'Fruits à coque', 'Céleri', 'Moutarde', 'Sésame', 'Sulfites', 'Lupin', 'Mollusques'];

@Injectable()
export class TechnicalSheetsService {
  constructor(private readonly prisma: PrismaService) {}

  private page(q?: TechnicalSheetListQueryDto) { const take = Math.min(q?.pageSize ?? 50, 200); const skip = ((q?.page ?? 1) - 1) * take; return { take, skip }; }

  private async assertInstalled(organizationId: string) {
    const org = await this.prisma.organization.findUnique({ where: { id: organizationId }, select: { stocksInstalledAt: true, technicalSheetsInstalledAt: true } });
    if (!org?.stocksInstalledAt) throw new BadRequestException('Le module Stocks doit être installé avant les Fiches Techniques.');
    if (!org.technicalSheetsInstalledAt) throw new BadRequestException('Le module Fiches Techniques n’est pas installé pour cette organisation.');
  }

  async install(organizationId: string, actor: Actor) {
    const org = await this.prisma.organization.findUnique({ where: { id: organizationId }, select: { stocksInstalledAt: true, rnmPricesInstalledAt: true, hrInstalledAt: true, planningInstalledAt: true } });
    if (!org?.stocksInstalledAt) throw new BadRequestException('Installation impossible: Stocks est obligatoire.');
    await this.prisma.$transaction(async (tx) => {
      await tx.organization.update({ where: { id: organizationId }, data: { technicalSheetsInstalledAt: new Date() } });
      await tx.technicalSheetCategory.createMany({ data: DEFAULT_CATEGORIES.map((name) => ({ organizationId, name })), skipDuplicates: true });
      await tx.technicalSheetAllergen.createMany({ data: DEFAULT_ALLERGENS.map((name) => ({ organizationId, name })), skipDuplicates: true });
      await tx.auditLog.create({ data: { organizationId, userId: actor.id, action: AuditAction.MODULE_TECHNICAL_SHEETS_INSTALLED, entityType: 'Module', entityId: 'technical-sheets', entityName: 'Fiches Techniques' } });
    });
    return { installed: true, installedApplications: this.installedApps({ ...org, technicalSheetsInstalledAt: new Date() }) };
  }

  async uninstall(organizationId: string, actor: Actor) {
    const org = await this.prisma.organization.findUnique({ where: { id: organizationId }, select: { stocksInstalledAt: true, rnmPricesInstalledAt: true, hrInstalledAt: true, planningInstalledAt: true } });
    await this.prisma.$transaction(async (tx) => {
      await tx.organization.update({ where: { id: organizationId }, data: { technicalSheetsInstalledAt: null } });
      await tx.auditLog.create({ data: { organizationId, userId: actor.id, action: AuditAction.MODULE_TECHNICAL_SHEETS_UNINSTALLED, entityType: 'Module', entityId: 'technical-sheets', entityName: 'Fiches Techniques' } });
    });
    return { installed: false, installedApplications: this.installedApps({ ...org, technicalSheetsInstalledAt: null }) };
  }

  async dashboard(organizationId: string) {
    await this.assertInstalled(organizationId);
    const [recipeCount, categoryCount, sheets, latest, used] = await Promise.all([
      this.prisma.technicalSheet.count({ where: { organizationId, isArchived: false } }),
      this.prisma.technicalSheetCategory.count({ where: { organizationId, isArchived: false } }),
      this.prisma.technicalSheet.findMany({ where: { organizationId, isArchived: false }, select: { totalCost: true } }),
      this.prisma.technicalSheet.findMany({ where: { organizationId }, include: this.recipeInclude(), orderBy: { updatedAt: 'desc' }, take: 8 }),
      this.prisma.technicalSheetIngredient.groupBy({ by: ['productId'], where: { organizationId }, _count: { productId: true }, orderBy: { _count: { productId: 'desc' } }, take: 10 }),
    ]);
    const products = await this.prisma.product.findMany({ where: { id: { in: used.map((u) => u.productId) } }, include: { unit: true, category: true } });
    const total = sheets.reduce((sum, s) => sum + Number(s.totalCost), 0);
    return { recipeCount, categoryCount, averageMaterialCost: sheets.length ? total / sheets.length : 0, usedStockProductsCount: used.length, latestRecipes: latest.map((s) => this.serializeRecipe(s)), topProducts: used.map((u) => { const product = products.find((p) => p.id === u.productId); return { productId: u.productId, name: product?.name ?? 'Produit Stocks', count: u._count.productId, product }; }), lastModifiedAt: latest[0]?.updatedAt?.toISOString?.() ?? null };
  }

  async listCategories(organizationId: string, q: TechnicalSheetListQueryDto = {}) { await this.assertInstalled(organizationId); return this.prisma.technicalSheetCategory.findMany({ where: { organizationId, ...(q.includeArchived ? {} : { isArchived: false }), name: q.search ? { contains: q.search, mode: 'insensitive' } : undefined }, orderBy: { name: 'asc' }, ...this.page(q) }); }
  async createCategory(organizationId: string, dto: UpsertRecipeCategoryDto) { await this.assertInstalled(organizationId); return this.prisma.technicalSheetCategory.create({ data: { ...dto, organizationId } }); }
  async updateCategory(organizationId: string, id: string, dto: UpsertRecipeCategoryDto) { await this.assertInstalled(organizationId); return this.prisma.technicalSheetCategory.update({ where: { id, organizationId }, data: dto }); }
  async archiveCategory(organizationId: string, id: string) { await this.assertInstalled(organizationId); return this.prisma.technicalSheetCategory.update({ where: { id, organizationId }, data: { isArchived: true, archivedAt: new Date() } }); }
  async listAllergens(organizationId: string, q: TechnicalSheetListQueryDto = {}) { await this.assertInstalled(organizationId); return this.prisma.technicalSheetAllergen.findMany({ where: { organizationId, ...(q.includeArchived ? {} : { isArchived: false }), name: q.search ? { contains: q.search, mode: 'insensitive' } : undefined }, orderBy: { name: 'asc' }, ...this.page(q) }); }
  async createAllergen(organizationId: string, dto: UpsertAllergenDto) { await this.assertInstalled(organizationId); return this.prisma.technicalSheetAllergen.create({ data: { name: dto.name, description: dto.description, organizationId } }); }
  async updateAllergen(organizationId: string, id: string, dto: UpsertAllergenDto) { await this.assertInstalled(organizationId); return this.prisma.technicalSheetAllergen.update({ where: { id, organizationId }, data: dto }); }
  async archiveAllergen(organizationId: string, id: string) { await this.assertInstalled(organizationId); return this.prisma.technicalSheetAllergen.update({ where: { id, organizationId }, data: { isArchived: true, archivedAt: new Date() } }); }

  async listRecipes(organizationId: string, q: TechnicalSheetListQueryDto = {}) {
    await this.assertInstalled(organizationId);
    const where = { organizationId, ...(q.includeArchived ? {} : { isArchived: false }), categoryId: q.categoryId, status: q.status, OR: q.search ? [{ name: { contains: q.search, mode: 'insensitive' as const } }, { description: { contains: q.search, mode: 'insensitive' as const } }, { category: { name: { contains: q.search, mode: 'insensitive' as const } } }, { ingredients: { some: { product: { name: { contains: q.search, mode: 'insensitive' as const } } } } }] : undefined };
    const [items, total] = await Promise.all([this.prisma.technicalSheet.findMany({ where, include: this.recipeInclude(), orderBy: { updatedAt: 'desc' }, ...this.page(q) }), this.prisma.technicalSheet.count({ where })]);
    return { items: items.map((i) => this.serializeRecipe(i)), total, page: q.page ?? 1, pageSize: Math.min(q.pageSize ?? 50, 200) };
  }

  async getRecipe(organizationId: string, id: string) { await this.assertInstalled(organizationId); const recipe = await this.prisma.technicalSheet.findFirst({ where: { id, organizationId }, include: this.recipeInclude(true) }); if (!recipe) throw new NotFoundException('Fiche technique introuvable'); return this.serializeRecipe(recipe); }

  async createRecipe(organizationId: string, actor: Actor, dto: UpsertTechnicalSheetDto) {
    await this.assertInstalled(organizationId); if (dto.categoryId) await this.ensureCategory(organizationId, dto.categoryId);
    return this.prisma.$transaction(async (tx) => { const created = await tx.technicalSheet.create({ data: this.recipeCreateData(organizationId, dto) }); await this.replaceChildren(tx, organizationId, created.id, dto); await this.history(tx, organizationId, created.id, actor.id, TechnicalSheetHistoryAction.CREATED, 'Création de la fiche technique'); await this.recalculateCostTx(tx, organizationId, created.id, actor.id, false); return this.serializeRecipe(await tx.technicalSheet.findUnique({ where: { id: created.id }, include: this.recipeInclude(true) })); });
  }

  async updateRecipe(organizationId: string, actor: Actor, id: string, dto: UpsertTechnicalSheetDto) {
    await this.assertInstalled(organizationId); await this.ensureRecipe(organizationId, id); if (dto.categoryId) await this.ensureCategory(organizationId, dto.categoryId);
    return this.prisma.$transaction(async (tx) => { await tx.technicalSheet.update({ where: { id, organizationId }, data: this.recipeUpdateData(dto) }); if (dto.ingredients) await this.replaceIngredients(tx, organizationId, id, dto.ingredients); if (dto.steps) await this.replaceSteps(tx, organizationId, id, dto.steps); await this.history(tx, organizationId, id, actor.id, TechnicalSheetHistoryAction.GENERAL_UPDATED, 'Modification de la fiche technique'); await this.recalculateCostTx(tx, organizationId, id, actor.id, false); return this.serializeRecipe(await tx.technicalSheet.findUnique({ where: { id }, include: this.recipeInclude(true) })); });
  }

  async archiveRecipe(organizationId: string, actor: Actor, id: string) { await this.assertInstalled(organizationId); await this.ensureRecipe(organizationId, id); return this.prisma.$transaction(async (tx) => { const sheet = await tx.technicalSheet.update({ where: { id, organizationId }, data: { status: TechnicalSheetStatus.ARCHIVED, isArchived: true, archivedAt: new Date() }, include: this.recipeInclude(true) }); await this.history(tx, organizationId, id, actor.id, TechnicalSheetHistoryAction.ARCHIVED, 'Archivage de la fiche technique'); return this.serializeRecipe(sheet); }); }

  async duplicateRecipe(organizationId: string, actor: Actor, id: string, dto: DuplicateTechnicalSheetDto) {
    await this.assertInstalled(organizationId); const source = await this.getRecipe(organizationId, id) as any; const name = dto.name || `${source.name} (copie)`;
    return this.prisma.$transaction(async (tx) => { const created = await tx.technicalSheet.create({ data: { organizationId, sourceTechnicalSheetId: id, name, description: dto.copyGeneral === false ? undefined : source.description, categoryId: dto.copyCategory === false ? undefined : source.categoryId, photoUrl: dto.copyPhoto === false ? undefined : source.photoUrl, photoDataUrl: dto.copyPhoto === false ? undefined : source.photoDataUrl, referencePortions: dto.copyGeneral === false ? 1 : source.referencePortions, preparationTimeMinutes: dto.copyGeneral === false ? 0 : source.preparationTimeMinutes, cookingTimeMinutes: dto.copyGeneral === false ? 0 : source.cookingTimeMinutes, totalTimeMinutes: dto.copyGeneral === false ? 0 : source.totalTimeMinutes, status: TechnicalSheetStatus.DRAFT } }); if (dto.copyIngredients !== false) await this.replaceIngredients(tx, organizationId, created.id, source.ingredients.map((i: any) => ({ productId: i.productId, unitId: i.unitId, quantity: Number(i.quantity), comment: i.comment, order: i.order, allergenIds: dto.copyAllergens === false ? [] : i.allergens.map((a: any) => a.id) }))); if (dto.copySteps !== false) await this.replaceSteps(tx, organizationId, created.id, source.steps.map((s: any) => ({ order: s.order, title: s.title, description: s.description, estimatedMinutes: s.estimatedMinutes ?? s.estimatedTimeMinutes }))); await this.history(tx, organizationId, created.id, actor.id, TechnicalSheetHistoryAction.DUPLICATED, `Duplication depuis ${source.name}`, { sourceTechnicalSheetId: id }); await this.recalculateCostTx(tx, organizationId, created.id, actor.id, false); return this.serializeRecipe(await tx.technicalSheet.findUnique({ where: { id: created.id }, include: this.recipeInclude(true) })); });
  }

  async recalculateCost(organizationId: string, actor: Actor, id: string) { await this.assertInstalled(organizationId); await this.ensureRecipe(organizationId, id); return this.serializeRecipe(await this.prisma.$transaction((tx) => this.recalculateCostTx(tx, organizationId, id, actor.id, true))); }
  async costs(organizationId: string, q: TechnicalSheetListQueryDto = {}) { return this.listRecipes(organizationId, q); }
  async historyList(organizationId: string, id: string, q: TechnicalSheetListQueryDto = {}) { await this.assertInstalled(organizationId); return this.prisma.technicalSheetHistory.findMany({ where: { organizationId, technicalSheetId: id }, include: { user: { select: { email: true, firstName: true, lastName: true } } }, orderBy: { createdAt: 'desc' }, ...this.page(q) }); }

  async simulate(organizationId: string, actor: Actor, dto: ProductionSimulationDto) {
    await this.assertInstalled(organizationId); const technicalSheetId = dto.technicalSheetId ?? dto.recipeId; if (!technicalSheetId) throw new BadRequestException('Fiche technique requise pour la simulation'); const recipe = await this.getRecipe(organizationId, technicalSheetId) as any;
    const factor = new Prisma.Decimal(dto.requestedPortions).div(recipe.referencePortions); const allergenNames = [...new Set<string>(recipe.ingredients.flatMap((i: any) => (i.allergens ?? []).map((a: any) => String(a.name))))];
    const lines = recipe.ingredients.map((i: any) => ({ ingredientId: i.id, productId: i.productId, productName: i.product?.name ?? i.productNameSnapshot, quantity: Number(new Prisma.Decimal(i.quantity).mul(factor)), unit: i.unit?.symbol, unitSymbol: i.unit?.symbol, estimatedCost: i.cost == null ? null : Number(new Prisma.Decimal(i.cost).mul(factor)), isCalculable: i.isCalculable, nonCalculableReason: i.nonCalculableReason, allergens: (i.allergens ?? []).map((a: any) => a.name).filter(Boolean) }));
    const sim = await this.prisma.technicalSheetSimulation.create({ data: { organizationId, technicalSheetId: recipe.id, requestedPortions: dto.requestedPortions, factor, totalEstimatedCost: new Prisma.Decimal(recipe.totalCost ?? 0).mul(factor), hasNonCalculableLines: recipe.hasNonCalculableLines, lines, allergenNames, createdById: actor.id }, include: { technicalSheet: true } });
    await this.prisma.technicalSheetHistory.create({ data: { organizationId, technicalSheetId: recipe.id, userId: actor.id, action: TechnicalSheetHistoryAction.SIMULATION_CREATED, summary: `Simulation pour ${dto.requestedPortions} portions` } });
    return { ...sim, recipeId: recipe.id, recipe, estimatedCost: Number(sim.totalEstimatedCost), allergens: allergenNames.map((name) => ({ id: name, name })), simulatedAt: sim.createdAt, lines };
  }

  async exportSimulation(organizationId: string, actor: Actor, simulationId: string, format: TechnicalSheetExportFormat) { await this.assertInstalled(organizationId); const sim = await this.prisma.technicalSheetSimulation.findFirst({ where: { id: simulationId, organizationId }, include: { technicalSheet: true } }); if (!sim) throw new NotFoundException('Simulation introuvable'); const filename = `production-${sim.technicalSheet.name}-${sim.id}.${format === TechnicalSheetExportFormat.CSV ? 'csv' : 'pdf'}`; await this.prisma.technicalSheetExport.create({ data: { organizationId, technicalSheetId: sim.technicalSheetId, simulationId: sim.id, format, filename, payload: { simulationId: sim.id }, createdById: actor.id } }); await this.prisma.technicalSheetHistory.create({ data: { organizationId, technicalSheetId: sim.technicalSheetId, userId: actor.id, action: TechnicalSheetHistoryAction.EXPORT_CREATED, summary: `Export ${format} préparé` } }); return format === TechnicalSheetExportFormat.CSV ? this.simulationCsv(sim as any) : this.simulationPdfText(sim as any); }

  private recipeInclude(full = false) { return { category: true, ingredients: { orderBy: { order: 'asc' as const }, include: { product: { include: { unit: true, category: true } }, unit: true, allergens: { include: { allergen: true } } } }, steps: { orderBy: { order: 'asc' as const } }, ...(full ? { costSnapshots: { orderBy: { createdAt: 'desc' as const }, take: 20 }, history: { orderBy: { createdAt: 'desc' as const }, take: 20, include: { user: { select: { email: true, firstName: true, lastName: true } } } } } : {}) }; }
  private serializeRecipe(sheet: any) { if (!sheet) return sheet; const ingredients = (sheet.ingredients ?? []).map((line: any) => ({ ...line, quantity: Number(line.quantity), cost: line.cost == null ? null : Number(line.cost), costTotal: line.cost == null ? null : Number(line.cost), allergens: (line.allergens ?? []).map((item: any) => item.allergen ?? item).filter(Boolean) })); const allergensById = new Map<string, any>(); ingredients.forEach((line: any) => (line.allergens ?? []).forEach((allergen: any) => allergensById.set(allergen.id ?? allergen.name, allergen))); return { ...sheet, referencePortions: Number(sheet.referencePortions ?? 0), portions: Number(sheet.referencePortions ?? 0), prepTimeMinutes: sheet.preparationTimeMinutes, cookTimeMinutes: sheet.cookingTimeMinutes, costTotal: sheet.totalCost == null ? null : Number(sheet.totalCost), totalCost: sheet.totalCost == null ? null : Number(sheet.totalCost), costPerPortion: sheet.costPerPortion == null ? null : Number(sheet.costPerPortion), costPerKg: sheet.costPerKg == null ? null : Number(sheet.costPerKg), costPerLiter: sheet.costPerLiter == null ? null : Number(sheet.costPerLiter), duplicatedFromId: sheet.sourceTechnicalSheetId, ingredients, steps: (sheet.steps ?? []).map((step: any) => ({ ...step, estimatedTimeMinutes: step.estimatedMinutes })), allergens: [...allergensById.values()], nonCalculableLinesCount: ingredients.filter((line: any) => !line.isCalculable).length }; }
  private recipeCreateData(organizationId: string, dto: UpsertTechnicalSheetDto): Prisma.TechnicalSheetUncheckedCreateInput { const prep = dto.preparationTimeMinutes ?? dto.prepTimeMinutes ?? 0; const cook = dto.cookingTimeMinutes ?? dto.cookTimeMinutes ?? 0; return { organizationId, name: dto.name, description: dto.description, categoryId: dto.categoryId || null, photoUrl: dto.photoUrl, photoDataUrl: dto.photoDataUrl, referencePortions: dto.referencePortions, preparationTimeMinutes: prep, cookingTimeMinutes: cook, totalTimeMinutes: dto.totalTimeMinutes ?? prep + cook, status: dto.status ?? TechnicalSheetStatus.DRAFT }; }
  private recipeUpdateData(dto: UpsertTechnicalSheetDto): Prisma.TechnicalSheetUncheckedUpdateInput { const prep = dto.preparationTimeMinutes ?? dto.prepTimeMinutes ?? 0; const cook = dto.cookingTimeMinutes ?? dto.cookTimeMinutes ?? 0; return { name: dto.name, description: dto.description, categoryId: dto.categoryId || null, photoUrl: dto.photoUrl, photoDataUrl: dto.photoDataUrl, referencePortions: dto.referencePortions, preparationTimeMinutes: prep, cookingTimeMinutes: cook, totalTimeMinutes: dto.totalTimeMinutes ?? prep + cook, status: dto.status ?? TechnicalSheetStatus.DRAFT }; }
  private async replaceChildren(tx: Tx, organizationId: string, id: string, dto: UpsertTechnicalSheetDto) { if (dto.ingredients) await this.replaceIngredients(tx, organizationId, id, dto.ingredients); if (dto.steps) await this.replaceSteps(tx, organizationId, id, dto.steps); }
  private async replaceIngredients(tx: Tx, organizationId: string, technicalSheetId: string, ingredients: NonNullable<UpsertTechnicalSheetDto['ingredients']>) { await tx.technicalSheetIngredient.deleteMany({ where: { technicalSheetId } }); for (const [idx, line] of ingredients.entries()) { const product = await tx.product.findFirst({ where: { id: line.productId, organizationId }, include: { unit: true } }); if (!product) throw new NotFoundException('Produit Stocks introuvable'); const unit = await tx.unit.findFirst({ where: { id: line.unitId, organizationId } }); if (!unit) throw new NotFoundException('Unité Stocks introuvable'); const ing = await tx.technicalSheetIngredient.create({ data: { organizationId, technicalSheetId, productId: product.id, unitId: unit.id, quantity: line.quantity, comment: line.comment, order: line.order ?? idx, productNameSnapshot: product.name, unitSymbolSnapshot: unit.symbol, productUnitIdSnapshot: product.unitId, productUnitSymbolSnapshot: product.unit.symbol, productArchivedSnapshot: product.isArchived } }); if (line.allergenIds?.length) await tx.technicalSheetIngredientAllergen.createMany({ data: line.allergenIds.map((allergenId) => ({ ingredientId: ing.id, allergenId })), skipDuplicates: true }); } }
  private async replaceSteps(tx: Tx, organizationId: string, technicalSheetId: string, steps: NonNullable<UpsertTechnicalSheetDto['steps']>) { await tx.technicalSheetStep.deleteMany({ where: { technicalSheetId } }); await tx.technicalSheetStep.createMany({ data: steps.map((s, idx) => ({ organizationId, technicalSheetId, order: s.order ?? idx, title: s.title ?? `Étape ${idx + 1}`, description: s.description ?? '', estimatedMinutes: s.estimatedMinutes ?? s.estimatedTimeMinutes })) }); }
  private async recalculateCostTx(tx: Tx, organizationId: string, technicalSheetId: string, userId: string | null, snapshot: boolean) { const recipe = await tx.technicalSheet.findUnique({ where: { id: technicalSheetId }, include: { ingredients: { include: { product: { include: { unit: true } }, unit: true } } } }); if (!recipe) throw new NotFoundException('Fiche technique introuvable'); let total = new Prisma.Decimal(0); const details: any[] = []; let hasNonCalculable = false; for (const line of recipe.ingredients) { const calc = await this.calculateLine(tx, organizationId, line); hasNonCalculable ||= !calc.isCalculable; if (calc.cost) total = total.add(calc.cost); await tx.technicalSheetIngredient.update({ where: { id: line.id }, data: { cost: calc.cost, unitPriceSnapshot: line.product.averagePrice, isCalculable: calc.isCalculable, nonCalculableReason: calc.reason, productArchivedSnapshot: line.product.isArchived } }); details.push({ ingredientId: line.id, productId: line.productId, productName: line.product.name, cost: calc.cost?.toString() ?? null, isCalculable: calc.isCalculable, reason: calc.reason }); } const perPortion = recipe.referencePortions.isZero() ? new Prisma.Decimal(0) : total.div(recipe.referencePortions); const updated = await tx.technicalSheet.update({ where: { id: technicalSheetId }, data: { totalCost: total, costPerPortion: perPortion, hasNonCalculableLines: hasNonCalculable, lastCostCalculationAt: new Date() }, include: this.recipeInclude(true) }); if (snapshot) await tx.technicalSheetCostSnapshot.create({ data: { organizationId, technicalSheetId, totalCost: total, costPerPortion: perPortion, hasNonCalculableLines: hasNonCalculable, lineDetails: details } }); await this.history(tx, organizationId, technicalSheetId, userId, TechnicalSheetHistoryAction.COST_RECALCULATED, 'Recalcul du coût matière', { totalCost: total.toString(), hasNonCalculableLines: hasNonCalculable }); return updated; }
  private async calculateLine(tx: Tx, organizationId: string, line: any) { if (line.product.isArchived) return { isCalculable: false, cost: null, reason: 'Produit Stocks archivé' }; let qty = new Prisma.Decimal(line.quantity); if (line.unitId !== line.product.unitId) { const conv = await tx.unitConversion.findFirst({ where: { organizationId, fromUnitId: line.unitId, toUnitId: line.product.unitId } }); if (!conv) return { isCalculable: false, cost: null, reason: 'Conversion unité indisponible dans Stocks' }; qty = qty.mul(conv.factor); } return { isCalculable: true, cost: qty.mul(line.product.averagePrice), reason: null }; }
  private async history(tx: Tx, organizationId: string, technicalSheetId: string, userId: string | null, action: TechnicalSheetHistoryAction, summary: string, details?: Prisma.InputJsonValue) { await tx.technicalSheetHistory.create({ data: { organizationId, technicalSheetId, userId: userId || null, action, summary, details } }); }
  private async ensureCategory(organizationId: string, id: string) { const item = await this.prisma.technicalSheetCategory.findFirst({ where: { id, organizationId } }); if (!item) throw new NotFoundException('Catégorie recette introuvable'); return item; }
  private async ensureRecipe(organizationId: string, id: string) { const item = await this.prisma.technicalSheet.findFirst({ where: { id, organizationId } }); if (!item) throw new NotFoundException('Fiche technique introuvable'); return item; }
  private installedApps(org: any) { return [...(org?.stocksInstalledAt ? ['stocks'] : []), ...(org?.rnmPricesInstalledAt ? ['rnm-prices'] : []), ...(org?.hrInstalledAt ? ['hr'] : []), ...(org?.planningInstalledAt ? ['planning'] : []), ...(org?.technicalSheetsInstalledAt ? ['technical-sheets'] : [])]; }
  private simulationCsv(sim: any) { const lines = Array.isArray(sim.lines) ? sim.lines : []; return ['Produit,Quantité,Unité,Coût estimé,Allergènes', ...lines.map((l: any) => [l.productName, l.quantity, l.unitSymbol ?? l.unit, l.estimatedCost ?? '', (l.allergens ?? []).join('|')].map((v) => `"${String(v).replace(/"/g, '""')}"`).join(','))].join('\n'); }
  private simulationPdfText(sim: any) { return `PDF - Simulation production\nFiche: ${sim.technicalSheet.name}\nPortions: ${sim.requestedPortions}\nAllergènes: ${sim.allergenNames.join(', ')}\n\n${JSON.stringify(sim.lines, null, 2)}`; }
}
