import { BadRequestException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { HrAbsenceStatus, HrEmployeeStatus, PlanningAssignmentOrigin, PlanningAssignmentStatus, PlanningConflictSeverity, PlanningHistoryAction, PlanningNotificationStatus, PlanningReplacementStatus, Prisma } from '@prisma/client';
import { PrismaService } from '../prisma/prisma.service';
import { AcceptReplacementDto, ApplyPlanningTemplateDto, GeneratePlanningDto, MovePlanningAssignmentDto, PlanningQueryDto, PrepareExportDto, UpsertHrAbsenceDto, UpsertHrSkillDto, UpsertPlanningAssignmentDto, UpsertPlanningNeedDto, UpsertPlanningTemplateDto } from './dto/planning.dto';

type Actor = { id: string; role: string };
const WRITE_ROLES = ['SUPER_ADMIN', 'Administrateur', 'ADMIN', 'Manager', 'MANAGER', 'Chef', 'Responsable'];
const ASSIGNMENT_INCLUDE = { employee: { include: { department: true, position: true, mainSite: true, skills: { include: { skill: true } } } }, department: true, position: true, site: true, rotation: true, absence: true, conflicts: true };

@Injectable()
export class PlanningService {
  constructor(private readonly prisma: PrismaService) {}
  private assertWrite(actor: Actor) { if (!WRITE_ROLES.includes(actor.role)) throw new ForbiddenException('Planning write access is restricted to managers and administrators'); }
  private page(q?: PlanningQueryDto) { const take = Math.min(q?.pageSize ?? 100, 200); return { take, skip: ((q?.page ?? 1) - 1) * take }; }
  private day(d = new Date()) { const x = new Date(d); x.setHours(0,0,0,0); return x; }
  private endDay(d = new Date()) { const x = new Date(d); x.setHours(23,59,59,999); return x; }
  private parseDate(v: string) { const d = new Date(v); if (Number.isNaN(+d)) throw new BadRequestException('Date invalide'); return d; }
  private parseTime(date: string, time: string) { if (/^\d{4}-\d{2}-\d{2}T/.test(time)) return this.parseDate(time); const [h,m] = time.split(':').map(Number); const d = this.day(this.parseDate(date)); if (Number.isNaN(h) || Number.isNaN(m)) throw new BadRequestException('Heure invalide'); d.setHours(h,m,0,0); return d; }

  async bootstrap(organizationId: string) {
    const [org, employees, departments, positions, rotations, sites, skills] = await Promise.all([
      this.prisma.organization.findUnique({ where: { id: organizationId }, select: { hrInstalledAt: true } }),
      this.prisma.hrEmployee.findMany({ where: { organizationId, isArchived: false }, include: { department: true, position: true, mainSite: true, rotationAssignments: { where: { endDate: null }, include: { rotation: true }, take: 1 }, skills: { include: { skill: true } } }, orderBy: [{ lastName: 'asc' }, { firstName: 'asc' }] }),
      this.prisma.hrDepartment.findMany({ where: { organizationId, isArchived: false }, orderBy: { name: 'asc' } }),
      this.prisma.hrPosition.findMany({ where: { organizationId, isArchived: false }, orderBy: { name: 'asc' } }),
      this.prisma.hrRotation.findMany({ where: { organizationId, isArchived: false }, orderBy: { name: 'asc' } }),
      this.prisma.site.findMany({ where: { organizationId, isArchived: false }, orderBy: { name: 'asc' } }),
      this.prisma.hrSkill.findMany({ where: { organizationId, isArchived: false }, orderBy: { name: 'asc' } }),
    ]);
    const hrReady = !!org?.hrInstalledAt && employees.length > 0 && departments.length > 0 && positions.length > 0;
    return { hrReady, prerequisites: { hrInstalled: !!org?.hrInstalledAt, employees: employees.length, departments: departments.length, positions: positions.length, rotations: rotations.length }, employees, departments, positions, rotations, sites, skills, emptyState: hrReady ? null : { title: 'Configurer RH pour planifier', message: 'Le Planning consomme les collaborateurs, services, postes, roulements, absences et compétences RH sans les dupliquer.' } };
  }

  async dashboard(organizationId: string) {
    const today = this.day(), end = this.endDay(), weekStart = this.weekStart(today), weekEnd = new Date(weekStart); weekEnd.setDate(weekStart.getDate()+6); weekEnd.setHours(23,59,59,999);
    const [presentToday, absentToday, departments, needs, replacements, weekAssignments, conflicts, employeesWithoutRotation] = await Promise.all([
      this.prisma.planningAssignment.count({ where: { organizationId, date: { gte: today, lte: end }, status: { not: PlanningAssignmentStatus.CANCELLED } } }),
      this.prisma.hrAbsence.count({ where: { organizationId, status: HrAbsenceStatus.APPROVED, startDate: { lte: end }, endDate: { gte: today } } }),
      this.prisma.hrDepartment.findMany({ where: { organizationId, isArchived: false } }),
      this.prisma.planningOperationalNeed.findMany({ where: { organizationId, startDate: { lte: end }, OR: [{ endDate: null }, { endDate: { gte: today } }] }, include: { department: true } }),
      this.prisma.planningReplacement.count({ where: { organizationId, status: { in: [PlanningReplacementStatus.TO_PROCESS, PlanningReplacementStatus.PROPOSED] } } }),
      this.prisma.planningAssignment.findMany({ where: { organizationId, date: { gte: weekStart, lte: weekEnd }, status: { not: PlanningAssignmentStatus.CANCELLED } }, include: { department: true } }),
      this.prisma.planningConflict.findMany({ where: { organizationId, resolvedAt: null }, orderBy: { createdAt: 'desc' }, take: 20 }),
      this.prisma.hrEmployee.count({ where: { organizationId, isArchived: false, rotationAssignments: { none: { endDate: null } } } }),
    ]);
    const coveredDepartmentIds = new Set(weekAssignments.map(a => a.departmentId));
    const underStaffed = await this.coverage(organizationId, today, end);
    const minutes = weekAssignments.reduce((s,a)=>s+Math.max(0,(+a.endTime-+a.startTime)/60000-(a.breakMinutes||0)),0);
    return { stats: { presentToday, absentToday, servicesCovered: departments.filter(d=>coveredDepartmentIds.has(d.id)).length, servicesUnderstaffed: underStaffed.filter(c=>['UNDERSTAFFED','PARTIAL','UNPLANNED'].includes(c.status)).length, replacementsNeeded: replacements, plannedHoursThisWeek: Math.round(minutes/60*10)/10 }, alerts: [...conflicts.map(c=>({ level: c.severity === 'BLOCKING' ? 'critical' : c.severity === 'STRONG_WARNING' ? 'warning' : 'info', code: c.code, label: c.label, details: c.details })), ...(employeesWithoutRotation ? [{ level: 'warning', code: 'EMPLOYEES_WITHOUT_ROTATION', label: `${employeesWithoutRotation} collaborateur(s) sans roulement`, details: {} }] : [])], coverage: underStaffed };
  }

  async listAssignments(organizationId: string, q: PlanningQueryDto = {}) {
    const start = q.startDate ? this.day(this.parseDate(q.startDate)) : q.date ? this.day(this.parseDate(q.date)) : undefined;
    const end = q.endDate ? this.endDay(this.parseDate(q.endDate)) : q.date ? this.endDay(this.parseDate(q.date)) : undefined;
    return this.prisma.planningAssignment.findMany({ where: { organizationId, employeeId: q.employeeId, departmentId: q.departmentId, positionId: q.positionId, siteId: q.siteId, status: q.status, date: start || end ? { gte: start, lte: end } : undefined }, include: ASSIGNMENT_INCLUDE, orderBy: [{ date: 'asc' }, { startTime: 'asc' }], ...this.page(q) });
  }

  async createAssignment(organizationId: string, actor: Actor, dto: UpsertPlanningAssignmentDto) {
    this.assertWrite(actor); await this.validateRefs(organizationId, dto);
    const data = this.assignmentData(organizationId, dto);
    const conflicts = await this.detectConflicts(organizationId, data);
    if (conflicts.some(c=>c.severity==='BLOCKING') && !dto.allowCriticalOverride) throw new BadRequestException({ message: 'Conflits bloquants détectés', conflicts });
    return this.prisma.$transaction(async tx => {
      const assignment = await tx.planningAssignment.create({ data: { ...data, absenceId: conflicts.find(c=>c.code==='APPROVED_ABSENCE')?.absenceId, createdById: actor.id }, include: ASSIGNMENT_INCLUDE });
      await this.persistConflicts(tx, organizationId, assignment.id, conflicts);
      await this.history(tx, organizationId, actor.id, PlanningHistoryAction.ASSIGNMENT_ADDED, 'PlanningAssignment', assignment.id, 'Affectation ajoutée', null, assignment);
      await this.notify(tx, organizationId, 'Nouvelle affectation', 'Votre planning a été mis à jour.', 'ASSIGNMENT_CREATED', 'PlanningAssignment', assignment.id, assignment.employee.userId, assignment.employeeId);
      return assignment;
    });
  }

  async updateAssignment(organizationId: string, actor: Actor, id: string, dto: UpsertPlanningAssignmentDto) {
    this.assertWrite(actor); const old = await this.getAssignment(organizationId, id); await this.validateRefs(organizationId, dto);
    const data = this.assignmentData(organizationId, dto); const conflicts = await this.detectConflicts(organizationId, data, id);
    if (conflicts.some(c=>c.severity==='BLOCKING') && !dto.allowCriticalOverride) throw new BadRequestException({ message: 'Conflits bloquants détectés', conflicts });
    return this.prisma.$transaction(async tx => {
      await tx.planningConflict.deleteMany({ where: { assignmentId: id, resolvedAt: null } });
      const assignment = await tx.planningAssignment.update({ where: { id, organizationId }, data: { ...data, absenceId: conflicts.find(c=>c.code==='APPROVED_ABSENCE')?.absenceId, updatedById: actor.id, allowCriticalOverride: !!dto.allowCriticalOverride, overrideReason: dto.overrideReason }, include: ASSIGNMENT_INCLUDE });
      await this.persistConflicts(tx, organizationId, id, conflicts);
      await this.history(tx, organizationId, actor.id, PlanningHistoryAction.ASSIGNMENT_UPDATED, 'PlanningAssignment', id, 'Affectation modifiée', old, assignment);
      return assignment;
    });
  }

  async moveAssignment(organizationId: string, actor: Actor, id: string, dto: MovePlanningAssignmentDto) {
    const current = await this.getAssignment(organizationId, id);
    return this.updateAssignment(organizationId, actor, id, { employeeId: dto.employeeId ?? current.employeeId, departmentId: dto.departmentId ?? current.departmentId, positionId: dto.positionId ?? current.positionId, siteId: dto.siteId ?? current.siteId ?? undefined, rotationId: current.rotationId ?? undefined, date: (dto.date ?? current.date.toISOString()).slice(0,10), startTime: dto.startTime ?? current.startTime.toISOString(), endTime: dto.endTime ?? current.endTime.toISOString(), breakMinutes: current.breakMinutes, status: PlanningAssignmentStatus.MODIFIED, origin: PlanningAssignmentOrigin.DRAG_DROP, comment: dto.comment ?? current.comment ?? undefined, allowCriticalOverride: dto.allowCriticalOverride, overrideReason: dto.overrideReason });
  }
  async deleteAssignment(organizationId: string, actor: Actor, id: string) { this.assertWrite(actor); const old = await this.getAssignment(organizationId,id); const updated = await this.prisma.planningAssignment.update({ where: { id, organizationId }, data: { status: PlanningAssignmentStatus.CANCELLED, updatedById: actor.id }, include: ASSIGNMENT_INCLUDE }); await this.prisma.planningHistory.create({ data: { organizationId, actorUserId: actor.id, action: PlanningHistoryAction.ASSIGNMENT_DELETED, entityType: 'PlanningAssignment', entityId: id, label: 'Affectation supprimée', oldValue: old as Prisma.InputJsonValue, newValue: updated as Prisma.InputJsonValue } }); return updated; }
  async getAssignment(organizationId: string, id: string) { const a = await this.prisma.planningAssignment.findFirst({ where: { id, organizationId }, include: ASSIGNMENT_INCLUDE }); if (!a) throw new NotFoundException('Affectation introuvable'); return a; }

  listNeeds(organizationId: string, q: PlanningQueryDto = {}) { return this.prisma.planningOperationalNeed.findMany({ where: { organizationId, departmentId: q.departmentId, siteId: q.siteId, positionId: q.positionId }, include: { department: true, site: true, position: true, requiredSkill: true }, orderBy: [{ startDate: 'asc' }, { startTime: 'asc' }], ...this.page(q) }); }
  async createNeed(organizationId: string, actor: Actor, dto: UpsertPlanningNeedDto) { this.assertWrite(actor); await this.validateNeedRefs(organizationId,dto); return this.prisma.planningOperationalNeed.create({ data: { organizationId, ...dto, startDate: this.parseDate(dto.startDate), endDate: dto.endDate ? this.parseDate(dto.endDate) : null, priority: dto.priority, createdById: actor.id }, include: { department: true, site: true, position: true, requiredSkill: true } }); }
  async updateNeed(organizationId: string, actor: Actor, id: string, dto: UpsertPlanningNeedDto) { this.assertWrite(actor); await this.validateNeedRefs(organizationId,dto); return this.prisma.planningOperationalNeed.update({ where: { id, organizationId }, data: { ...dto, startDate: this.parseDate(dto.startDate), endDate: dto.endDate ? this.parseDate(dto.endDate) : null }, include: { department: true, site: true, position: true, requiredSkill: true } }); }
  async deleteNeed(organizationId: string, actor: Actor, id: string) { this.assertWrite(actor); return this.prisma.planningOperationalNeed.delete({ where: { id, organizationId } }); }

  async listAbsences(organizationId: string, q: PlanningQueryDto={}) { const start=q.startDate?this.parseDate(q.startDate):undefined,end=q.endDate?this.parseDate(q.endDate):undefined; return this.prisma.hrAbsence.findMany({ where: { organizationId, employeeId: q.employeeId, status: q.absenceStatus, startDate: end?{ lte:end}:undefined, endDate: start?{ gte:start}:undefined }, include: { employee: { include: { department: true, position: true } }, validator: { select: { id: true, firstName: true, lastName: true, email: true } } }, orderBy: { startDate: 'asc' }, ...this.page(q) }); }
  async createAbsence(organizationId: string, actor: Actor, dto: UpsertHrAbsenceDto) { this.assertWrite(actor); await this.ensureEmployee(organizationId,dto.employeeId); const absence = await this.prisma.hrAbsence.create({ data: { organizationId, ...dto, startDate: this.parseDate(dto.startDate), endDate: this.parseDate(dto.endDate), validatorId: dto.status === HrAbsenceStatus.APPROVED ? actor.id : undefined, validatedAt: dto.status === HrAbsenceStatus.APPROVED ? new Date() : undefined }, include: { employee: true } }); await this.detectAbsenceImpact(organizationId, actor, absence.id); return absence; }
  async updateAbsence(organizationId: string, actor: Actor, id: string, dto: UpsertHrAbsenceDto) { this.assertWrite(actor); const absence = await this.prisma.hrAbsence.update({ where: { id, organizationId }, data: { ...dto, startDate: this.parseDate(dto.startDate), endDate: this.parseDate(dto.endDate), validatorId: dto.status === HrAbsenceStatus.APPROVED ? actor.id : undefined, validatedAt: dto.status === HrAbsenceStatus.APPROVED ? new Date() : undefined }, include: { employee: true } }); await this.detectAbsenceImpact(organizationId, actor, id); return absence; }

  listTemplates(organizationId: string, q: PlanningQueryDto={}) { return this.prisma.planningTemplate.findMany({ where: { organizationId, isArchived: false, departmentId: q.departmentId, siteId: q.siteId, name: q.search ? { contains: q.search, mode: 'insensitive' } : undefined }, include: { department: true, site: true }, orderBy: { name: 'asc' }, ...this.page(q) }); }
  async createTemplate(organizationId: string, actor: Actor, dto: UpsertPlanningTemplateDto) { this.assertWrite(actor); return this.prisma.planningTemplate.create({ data: { organizationId, name: dto.name, description: dto.description, periodType: dto.periodType, departmentId: dto.departmentId, siteId: dto.siteId, content: (dto.content ?? { slots: [] }) as Prisma.InputJsonValue, createdById: actor.id }, include: { department: true, site: true } }); }
  async applyTemplate(organizationId: string, actor: Actor, id: string, dto: ApplyPlanningTemplateDto) { this.assertWrite(actor); const tpl = await this.prisma.planningTemplate.findFirst({ where: { id, organizationId } }); if(!tpl) throw new NotFoundException('Modèle introuvable'); const preview = { templateId: id, created: [], conflicts: [], message: 'Application préparée: les modèles définissent besoins et créneaux sans écraser les affectations existantes.' }; const app = await this.prisma.planningTemplateApplication.create({ data: { organizationId, templateId: id, siteId: dto.siteId, startDate: this.parseDate(dto.startDate), endDate: this.parseDate(dto.endDate), preview, applied: !!dto.apply, appliedById: dto.apply ? actor.id : undefined, appliedAt: dto.apply ? new Date() : undefined } }); if(dto.apply) await this.prisma.planningHistory.create({ data: { organizationId, actorUserId: actor.id, action: PlanningHistoryAction.TEMPLATE_APPLIED, entityType: 'PlanningTemplate', entityId: id, label: 'Modèle appliqué', newValue: preview } }); return app; }

  async generate(organizationId: string, actor: Actor, dto: GeneratePlanningDto) { this.assertWrite(actor); const start=this.day(this.parseDate(dto.startDate)), end=this.endDay(this.parseDate(dto.endDate)); const preview = await this.buildGenerationPreview(organizationId,start,end,dto.siteId); const gen = await this.prisma.planningGeneration.create({ data: { organizationId, siteId: dto.siteId, startDate: start, endDate: end, preview: preview as Prisma.InputJsonValue, parameters: dto as unknown as Prisma.InputJsonValue, launchedById: actor.id } }); await this.prisma.planningHistory.create({ data: { organizationId, actorUserId: actor.id, action: PlanningHistoryAction.GENERATION_STARTED, entityType: 'PlanningGeneration', entityId: gen.id, label: 'Génération lancée', newValue: preview as Prisma.InputJsonValue } }); if(dto.apply) return this.applyGeneration(organizationId, actor, gen.id); return gen; }
  async applyGeneration(organizationId: string, actor: Actor, id: string) { this.assertWrite(actor); const gen = await this.prisma.planningGeneration.findFirst({ where: { id, organizationId } }); if(!gen) throw new NotFoundException('Génération introuvable'); const proposed = ((gen.preview as any)?.assignments ?? []) as any[]; return this.prisma.$transaction(async tx => { const created=[]; for(const p of proposed){ const conflicts = await this.detectConflicts(organizationId, this.assignmentData(organizationId, p)); if(conflicts.some(c=>c.severity==='BLOCKING')) continue; created.push(await tx.planningAssignment.create({ data: { ...this.assignmentData(organizationId,p), origin: PlanningAssignmentOrigin.AUTO_GENERATION, createdById: actor.id } })); } const updated=await tx.planningGeneration.update({ where: { id, organizationId }, data: { applied: true, appliedById: actor.id, appliedAt: new Date() } }); await this.history(tx, organizationId, actor.id, PlanningHistoryAction.GENERATION_APPLIED, 'PlanningGeneration', id, 'Génération appliquée', null, { created: created.length }); return { ...updated, createdAssignments: created }; }); }

  async listReplacements(organizationId: string, q: PlanningQueryDto={}) { return this.prisma.planningReplacement.findMany({ where: { organizationId, status: q.replacementStatus }, include: { assignment: { include: ASSIGNMENT_INCLUDE }, absence: true, absentEmployee: { include: { department: true, position: true } }, replacementEmployee: { include: { department: true, position: true } } }, orderBy: { createdAt: 'desc' }, ...this.page(q) }); }
  async proposeReplacements(organizationId: string, actor: Actor) { this.assertWrite(actor); const absences=await this.prisma.hrAbsence.findMany({ where: { organizationId, status: HrAbsenceStatus.APPROVED }, include: { employee: true } }); for(const a of absences) await this.detectAbsenceImpact(organizationId, actor, a.id); return this.listReplacements(organizationId); }
  async acceptReplacement(organizationId: string, actor: Actor, id: string, dto: AcceptReplacementDto) { this.assertWrite(actor); const repl=await this.prisma.planningReplacement.findFirst({ where:{id,organizationId}, include:{assignment:true} }); if(!repl) throw new NotFoundException('Remplacement introuvable'); const updated=await this.prisma.planningReplacement.update({ where:{id,organizationId}, data:{ replacementEmployeeId:dto.replacementEmployeeId, status:PlanningReplacementStatus.ACCEPTED, acceptedById:actor.id, acceptedAt:new Date(), comment:dto.comment } }); if(repl.assignment) await this.prisma.planningAssignment.update({ where:{id:repl.assignment.id}, data:{ employeeId:dto.replacementEmployeeId, origin:PlanningAssignmentOrigin.REPLACEMENT, status:PlanningAssignmentStatus.MODIFIED, updatedById:actor.id } }); return updated; }

  listHistory(organizationId: string, q: PlanningQueryDto={}) { const start=q.startDate?this.parseDate(q.startDate):undefined,end=q.endDate?this.parseDate(q.endDate):undefined; return this.prisma.planningHistory.findMany({ where:{organizationId, createdAt:start||end?{gte:start,lte:end}:undefined}, include:{actorUser:{select:{id:true,email:true,firstName:true,lastName:true}}}, orderBy:{createdAt:'desc'}, ...this.page(q) }); }
  archiveHistory(organizationId: string, actor: Actor, startDate: string, endDate: string) { this.assertWrite(actor); const start=this.parseDate(startDate), end=this.parseDate(endDate); const period=`${start.toISOString().slice(0,10)}_${end.toISOString().slice(0,10)}`; return this.prisma.planningHistory.updateMany({ where:{organizationId,createdAt:{gte:start,lte:end}}, data:{isArchived:true,archivedPeriod:period} }); }
  listNotifications(organizationId: string, userId: string) { return this.prisma.planningNotification.findMany({ where:{organizationId, OR:[{recipientUserId:userId},{recipientUserId:null}]}, orderBy:{createdAt:'desc'}, take:100 }); }
  markNotificationRead(organizationId: string, id: string) { return this.prisma.planningNotification.update({ where:{id,organizationId}, data:{status:PlanningNotificationStatus.READ, readAt:new Date()} }); }
  async prepareExport(organizationId: string, actor: Actor, dto: PrepareExportDto) { this.assertWrite(actor); const exp=await this.prisma.planningExport.create({ data:{ organizationId, requestedById:actor.id, ...dto, startDate:this.parseDate(dto.startDate), endDate:this.parseDate(dto.endDate), filters:(dto.filters??{}) as Prisma.InputJsonValue } }); await this.prisma.planningHistory.create({ data:{ organizationId, actorUserId:actor.id, action:PlanningHistoryAction.EXPORT_GENERATED, entityType:'PlanningExport', entityId:exp.id, label:'Export préparé', newValue: exp as Prisma.InputJsonValue } }); return { ...exp, prepared: true, message: 'Export préparé pour génération PDF/Excel/impression.' }; }

  async listSkills(organizationId: string) { return this.prisma.hrSkill.findMany({ where:{organizationId,isArchived:false}, orderBy:{name:'asc'} }); }
  async createSkill(organizationId: string, actor: Actor, dto: UpsertHrSkillDto) { this.assertWrite(actor); return this.prisma.hrSkill.create({ data:{organizationId,...dto} }); }
  async setEmployeeSkills(organizationId: string, actor: Actor, employeeId: string, skillIds: string[]) { this.assertWrite(actor); await this.ensureEmployee(organizationId,employeeId); await this.prisma.hrSkill.count({ where:{organizationId,id:{in:skillIds}} }); return this.prisma.$transaction(async tx=>{ await tx.hrEmployeeSkill.deleteMany({where:{employeeId}}); if(skillIds.length) await tx.hrEmployeeSkill.createMany({data:skillIds.map(skillId=>({employeeId,skillId})), skipDuplicates:true}); return tx.hrEmployee.findFirst({ where:{id:employeeId,organizationId}, include:{skills:{include:{skill:true}}} }); }); }

  private assignmentData(organizationId: string, dto: UpsertPlanningAssignmentDto) { return { organizationId, employeeId:dto.employeeId, departmentId:dto.departmentId, positionId:dto.positionId, siteId:dto.siteId ?? null, rotationId:dto.rotationId ?? null, date:this.day(this.parseDate(dto.date)), startTime:this.parseTime(dto.date,dto.startTime), endTime:this.parseTime(dto.date,dto.endTime), breakMinutes:dto.breakMinutes ?? 0, status:dto.status ?? PlanningAssignmentStatus.PLANNED, origin:dto.origin ?? PlanningAssignmentOrigin.MANUAL, comment:dto.comment ?? null, allowCriticalOverride:!!dto.allowCriticalOverride, overrideReason:dto.overrideReason ?? null }; }
  private async validateRefs(organizationId: string, dto: UpsertPlanningAssignmentDto) { const [e,d,p]=await Promise.all([this.ensureEmployee(organizationId,dto.employeeId), this.prisma.hrDepartment.findFirst({where:{id:dto.departmentId,organizationId,isArchived:false}}), this.prisma.hrPosition.findFirst({where:{id:dto.positionId,organizationId,isArchived:false}})]); if(!d) throw new NotFoundException('Service RH introuvable'); if(!p) throw new NotFoundException('Poste RH introuvable'); if(e.departmentId!==dto.departmentId) {/* warning handled in controls */} if(dto.siteId && !(await this.prisma.site.findFirst({where:{id:dto.siteId,organizationId,isArchived:false}}))) throw new NotFoundException('Site introuvable'); }
  private async validateNeedRefs(organizationId:string,dto:UpsertPlanningNeedDto){ if(!(await this.prisma.hrDepartment.findFirst({where:{id:dto.departmentId,organizationId,isArchived:false}}))) throw new NotFoundException('Service RH introuvable'); if(dto.positionId && !(await this.prisma.hrPosition.findFirst({where:{id:dto.positionId,organizationId,isArchived:false}}))) throw new NotFoundException('Poste RH introuvable'); if(dto.requiredSkillId && !(await this.prisma.hrSkill.findFirst({where:{id:dto.requiredSkillId,organizationId,isArchived:false}}))) throw new NotFoundException('Compétence RH introuvable'); }
  private async ensureEmployee(organizationId:string,id:string){ const e=await this.prisma.hrEmployee.findFirst({where:{id,organizationId,isArchived:false},include:{skills:true,user:true}}); if(!e) throw new NotFoundException('Collaborateur RH introuvable'); return e; }
  private async detectConflicts(organizationId:string,data:any,excludeId?:string){ const conflicts:any[]=[]; const employee=await this.prisma.hrEmployee.findFirst({where:{id:data.employeeId,organizationId},include:{skills:true}}); if(!employee || employee.isArchived || employee.status!==HrEmployeeStatus.ACTIVE) conflicts.push({severity:'BLOCKING',code:'EMPLOYEE_UNAVAILABLE',label:'Collaborateur inactif ou archivé'}); const absence=await this.prisma.hrAbsence.findFirst({where:{organizationId,employeeId:data.employeeId,status:HrAbsenceStatus.APPROVED,startDate:{lte:data.endTime},endDate:{gte:data.startTime}}}); if(absence) conflicts.push({severity:'BLOCKING',code:'APPROVED_ABSENCE',label:'Collaborateur affecté pendant une absence validée',absenceId:absence.id}); const overlap=await this.prisma.planningAssignment.findFirst({where:{organizationId,employeeId:data.employeeId,id:excludeId?{not:excludeId}:undefined,status:{not:PlanningAssignmentStatus.CANCELLED},startTime:{lt:data.endTime},endTime:{gt:data.startTime}}}); if(overlap) conflicts.push({severity:'BLOCKING',code:'TIME_OVERLAP',label:'Chevauchement horaire bloquant'}); if(employee && employee.departmentId!==data.departmentId) conflicts.push({severity:'STRONG_WARNING',code:'DEPARTMENT_MISMATCH',label:'Service différent du service habituel'}); if(employee && employee.positionId!==data.positionId) conflicts.push({severity:'STRONG_WARNING',code:'POSITION_MISMATCH',label:'Poste différent du poste habituel'}); const dayAssignments=await this.prisma.planningAssignment.findMany({where:{organizationId,employeeId:data.employeeId,date:data.date,status:{not:PlanningAssignmentStatus.CANCELLED},id:excludeId?{not:excludeId}:undefined}}); const minutes=dayAssignments.reduce((s,a)=>s+(+a.endTime-+a.startTime)/60000-(a.breakMinutes||0),0)+(+data.endTime-+data.startTime)/60000-(data.breakMinutes||0); if(minutes>600) conflicts.push({severity:'STRONG_WARNING',code:'DAILY_AMPLITUDE',label:'Amplitude journalière supérieure à 10h'}); const ws=this.weekStart(data.date), we=new Date(ws); we.setDate(ws.getDate()+6); we.setHours(23,59,59,999); const week=await this.prisma.planningAssignment.findMany({where:{organizationId,employeeId:data.employeeId,date:{gte:ws,lte:we},status:{not:PlanningAssignmentStatus.CANCELLED},id:excludeId?{not:excludeId}:undefined}}); const wmin=week.reduce((s,a)=>s+(+a.endTime-+a.startTime)/60000-(a.breakMinutes||0),0)+(+data.endTime-+data.startTime)/60000-(data.breakMinutes||0); if(wmin>48*60) conflicts.push({severity:'STRONG_WARNING',code:'WEEKLY_LOAD',label:'Charge hebdomadaire supérieure à 48h'}); return conflicts; }
  private async persistConflicts(tx:Prisma.TransactionClient,organizationId:string,assignmentId:string,conflicts:any[]){ for(const c of conflicts) await tx.planningConflict.create({data:{organizationId,assignmentId,severity:c.severity as PlanningConflictSeverity,code:c.code,label:c.label,details:c as Prisma.InputJsonValue}}); }
  private weekStart(d:Date){ const x=this.day(d); const day=x.getDay()||7; x.setDate(x.getDate()-day+1); return x; }
  private async history(tx:Prisma.TransactionClient,organizationId:string,actorUserId:string|undefined,action:PlanningHistoryAction,entityType:string,entityId:string|undefined,label:string,oldValue:any,newValue:any){ await tx.planningHistory.create({data:{organizationId,actorUserId,action,entityType,entityId,label,oldValue:oldValue as Prisma.InputJsonValue,newValue:newValue as Prisma.InputJsonValue}}); }
  private async notify(tx:Prisma.TransactionClient,organizationId:string,title:string,message:string,eventType:string,entityType?:string,entityId?:string,recipientUserId?:string|null,recipientEmployeeId?:string|null){ await tx.planningNotification.create({data:{organizationId,title,message,eventType,entityType,entityId,recipientUserId:recipientUserId||null,recipientEmployeeId:recipientEmployeeId||null}}); await tx.planningHistory.create({data:{organizationId,action:PlanningHistoryAction.NOTIFICATION_CREATED,entityType:'PlanningNotification',label:title,newValue:{message,eventType} as Prisma.InputJsonValue}}); }
  private async coverage(organizationId:string,start:Date,end:Date){ const needs=await this.prisma.planningOperationalNeed.findMany({where:{organizationId,startDate:{lte:end},OR:[{endDate:null},{endDate:{gte:start}}]},include:{department:true,site:true,position:true}}); const assignments=await this.prisma.planningAssignment.findMany({where:{organizationId,date:{gte:this.day(start),lte:this.endDay(end)},status:{not:PlanningAssignmentStatus.CANCELLED}}}); return needs.map(n=>{ const count=assignments.filter(a=>a.departmentId===n.departmentId && (!n.siteId||a.siteId===n.siteId) && (!n.positionId||a.positionId===n.positionId)).length; const status=count>=n.requiredCount?'COVERED':count===0?'UNPLANNED':'PARTIAL'; return { need:n, plannedCount:count, requiredCount:n.requiredCount, status: count<n.requiredCount && count>0 ? 'UNDERSTAFFED' : status }; }); }
  private async detectAbsenceImpact(organizationId:string,actor:Actor,absenceId:string){ const absence=await this.prisma.hrAbsence.findFirst({where:{id:absenceId,organizationId}}); if(!absence || absence.status!==HrAbsenceStatus.APPROVED) return; const impacted=await this.prisma.planningAssignment.findMany({where:{organizationId,employeeId:absence.employeeId,status:{not:PlanningAssignmentStatus.CANCELLED},startTime:{lte:absence.endDate},endTime:{gte:absence.startDate}}}); for(const a of impacted){ await this.prisma.planningReplacement.upsert({where:{id:`00000000-0000-0000-0000-000000000000`}, update:{}, create:{organizationId,assignmentId:a.id,absenceId,absentEmployeeId:absence.employeeId,status:PlanningReplacementStatus.TO_PROCESS,requestedById:actor.id,rationale: await this.replacementCandidates(organizationId,a) as Prisma.InputJsonValue} }).catch(async()=>{ const exists=await this.prisma.planningReplacement.findFirst({where:{organizationId,assignmentId:a.id,absenceId}}); if(!exists) await this.prisma.planningReplacement.create({data:{organizationId,assignmentId:a.id,absenceId,absentEmployeeId:absence.employeeId,status:PlanningReplacementStatus.TO_PROCESS,requestedById:actor.id,rationale: await this.replacementCandidates(organizationId,a) as Prisma.InputJsonValue}}); }); } }
  private async replacementCandidates(organizationId:string,a:any){ const emps=await this.prisma.hrEmployee.findMany({where:{organizationId,isArchived:false,status:HrEmployeeStatus.ACTIVE,id:{not:a.employeeId}},include:{skills:{include:{skill:true}},department:true,position:true}}); const busy=await this.prisma.planningAssignment.findMany({where:{organizationId,startTime:{lt:a.endTime},endTime:{gt:a.startTime},status:{not:PlanningAssignmentStatus.CANCELLED}}}); const busyIds=new Set(busy.map(b=>b.employeeId)); return emps.map(e=>({employeeId:e.id,score:(e.departmentId===a.departmentId?40:0)+(e.positionId===a.positionId?30:0)+(!busyIds.has(e.id)?20:-100),reasons:[e.departmentId===a.departmentId?'Même service':'Service différent',e.positionId===a.positionId?'Même poste':'Poste différent',!busyIds.has(e.id)?'Disponible':'Conflit horaire']})).filter(c=>c.score>0).sort((x,y)=>y.score-x.score).slice(0,5); }
  private async buildGenerationPreview(organizationId:string,start:Date,end:Date,siteId?:string){ const [needs,employees,absences,existing]=await Promise.all([this.prisma.planningOperationalNeed.findMany({where:{organizationId,siteId:siteId??undefined},include:{department:true,position:true}}),this.prisma.hrEmployee.findMany({where:{organizationId,isArchived:false,status:HrEmployeeStatus.ACTIVE,mainSiteId:siteId??undefined},include:{rotationAssignments:{where:{endDate:null},include:{rotation:true},take:1},skills:true}}),this.prisma.hrAbsence.findMany({where:{organizationId,status:HrAbsenceStatus.APPROVED,startDate:{lte:end},endDate:{gte:start}}}),this.prisma.planningAssignment.findMany({where:{organizationId,date:{gte:start,lte:end},status:{not:PlanningAssignmentStatus.CANCELLED}}})]); const assignments:any[]=[], alerts:any[]=[]; for(const need of needs){ for(let d=new Date(start); d<=end; d.setDate(d.getDate()+1)){ const already=existing.filter(a=>a.departmentId===need.departmentId && a.date.toDateString()===d.toDateString()).length + assignments.filter(a=>a.departmentId===need.departmentId && a.date===d.toISOString().slice(0,10)).length; for(let i=already;i<need.requiredCount;i++){ const candidate=employees.find(e=>e.departmentId===need.departmentId && !absences.some(ab=>ab.employeeId===e.id && ab.startDate<=d && ab.endDate>=d) && !assignments.some(a=>a.employeeId===e.id && a.date===d.toISOString().slice(0,10))); if(!candidate){ alerts.push({level:'critical',code:'UNCOVERED_NEED',needId:need.id,date:d.toISOString().slice(0,10)}); continue; } assignments.push({employeeId:candidate.id,departmentId:need.departmentId,positionId:need.positionId??candidate.positionId,siteId:need.siteId??siteId,date:d.toISOString().slice(0,10),startTime:need.startTime,endTime:need.endTime,breakMinutes:30,status:PlanningAssignmentStatus.PLANNED,origin:PlanningAssignmentOrigin.AUTO_GENERATION}); } } } return { assignments, alerts, summary:{created:assignments.length,uncovered:alerts.length}, deterministicRules:['besoins par service','collaborateur actif','absence validée exclue','pas de doublon journalier'] }; }
}
