"""Fill missing French catalog entries with a locally installed Argos model.

This is an optional maintainer tool. The application never imports Argos and
does not perform network translation at runtime.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

import argostranslate.translate


ROOT = Path(__file__).resolve().parents[2]
SOURCE_PATH = ROOT / "apps/web/src/i18n/fr-source.generated.json"
CATALOG_PATH = ROOT / "apps/web/src/i18n/en.generated.ts"

FRENCH_SIGNAL = re.compile(
    r"[àâçéèêëîïôùûüÿœ]|\b(?:accueil|achats?|ajouter|annuler|aucun(?:e)?|catégories?|"
    r"choisir|commandes?|confirmer|connexion|créer|données?|enregistrer|"
    r"établissements?|fermer|fiches?|fournisseurs?|français|général|historique|"
    r"jours?|langue|lignes?|modifier|nouveau|paramètres|plannings?|produits?|"
    r"réceptions?|rechercher|retour|sauvegardes?|sélectionner|services?|stocks?|"
    r"suivant|supprimer|tableau|terminer|utilisateurs?|valider|votre|vos|vous)\b",
    re.IGNORECASE,
)

PROTECTED_TERMS = [
    "ToqueHub",
    "HACCP",
    "Mistral",
    "FranceAgriMer",
    "RNM",
    "FlatPay",
    "Fennoa",
    "Google",
    "Microsoft",
    "MQTT",
    "OCR",
    "SKU",
    "CSV",
    "PDF",
    "API",
    "JWT",
]


def read_catalog() -> dict[str, str]:
    source = CATALOG_PATH.read_text(encoding="utf-8")
    prefix = "export const englishCatalog: Readonly<Record<string, string>> = "
    start = source.index(prefix) + len(prefix)
    raw = json.loads(source[start:].strip().removesuffix(";"))
    return {
        re.sub(r"\s+", " ", key).strip(): re.sub(r"\s+", " ", value).strip()
        for key, value in raw.items()
    }


def protect(value: str) -> str:
    for index, term in enumerate(PROTECTED_TERMS):
        value = value.replace(term, f"__TERM_{index:02d}__")
    return value


def restore(value: str) -> str:
    for index, term in enumerate(PROTECTED_TERMS):
        value = re.sub(
            rf"_*TERM[\s_]*{index:02d}_*",
            term,
            value,
            flags=re.IGNORECASE,
        )
        value = re.sub(rf"(?<=\w){re.escape(term)}", f" {term}", value)
        value = re.sub(rf"{re.escape(term)}(?=\w)", f"{term} ", value)
    return value


entries = json.loads(SOURCE_PATH.read_text(encoding="utf-8"))
catalog = read_catalog()
missing = [
    entry["text"]
    for entry in entries
    if entry["text"] not in catalog and FRENCH_SIGNAL.search(entry["text"])
]

print(f"Translating {len(missing)} missing French-looking UI/API strings locally...", flush=True)
for index, source in enumerate(missing, start=1):
    target = restore(argostranslate.translate.translate(protect(source), "fr", "en")).strip()
    if target and target != source:
        catalog[source] = target
    if index % 50 == 0 or index == len(missing):
        print(f"Translated {index}/{len(missing)} strings.", flush=True)

catalog = {source: restore(target) for source, target in catalog.items()}

contents = (
    "// Generated by scripts/i18n/translate-web-catalog.mjs and completed with Argos.\n"
    "export const englishCatalog: Readonly<Record<string, string>> = "
    f"{json.dumps(dict(sorted(catalog.items())), ensure_ascii=False, indent=2)};\n"
)
CATALOG_PATH.write_text(contents, encoding="utf-8", newline="\n")
print(f"Wrote {len(catalog)} translations to {CATALOG_PATH.relative_to(ROOT)}.", flush=True)
