// @ts-nocheck
import { BadRequestException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { AuditAction, MenuExportFormat, MenuHistoryAction, MenuProductionGenerationMode, MenuStatus, Prisma, ProductionMaterialStatus, ProductionPriority } from '@prisma/client';
import { PrismaService } from '../prisma/prisma.service';

const WRITE_ROLES = ['SUPER_ADMIN', 'Administrateur', 'Manager', 'Chef', 'Second'];
const MANAGER_ROLES = ['SUPER_ADMIN', 'Administrateur', 'Manager', 'Chef'];
const DEFAULT_DIETS = ['Standard', 'Sans porc', 'Mixé', 'Haché', 'Diabétique', 'Sans sel', 'Végétarien', 'Végétalien', 'Texture modifiée', 'Autre'];
const DEFAULT_GUEST_GROUPS = [
  ['Résidents', 'RESIDENTS'], ['Patients', 'PATIENTS'], ['Élèves', 'STUDENTS'], ['Clients', 'CLIENTS'], ['Personnel', 'STAFF'], ['Invités', 'GUESTS'], ['Autre', 'OTHER'],
];
type Actor = { id: string; role: string };

@Injectable()
export class MenusService {
  constructor(private readonly prisma: PrismaService) {}

  private assertWrite(actor: Actor) { if (!WRITE_ROLES.includes(actor.role)) throw new ForbiddenException('Droits Menus insuffisants'); }
  private assertManager(actor: Actor) { if (!MANAGER_ROLES.includes(actor.role)) throw new ForbiddenException('Action réservée aux managers Menus'); }
  private page(q: any = {}) { const take = Math.min(q.pageSize ?? 50, 200); return { take, skip: ((q.page ?? 1) - 1) * take }; }
  private dayRange(date = new Date()) { const start = new Date(date); start.setHours(0, 0, 0, 0); const end = new Date(start); end.setDate(end.getDate() + 1); return { start, end }; }
  private dateRange(q: any = {}) { return q.date ? this.dayRange(new Date(q.date)) : { start: q.startDate ? new Date(q.startDate) : undefined, end: q.endDate ? new Date(q.endDate) : undefined }; }

  private async assertInstalled(organizationId: string) {
    const org = await this.prisma.organization.findUnique({ where: { id: organizationId }, select: { technicalSheetsInstalledAt: true, productionInstalledAt: true, menusInstalledAt: true } });
    if (!org?.technicalSheetsInstalledAt) throw new BadRequestException('Le module Fiches Techniques doit être installé avant Menus.');
    if (!org.productionInstalledAt) throw new BadRequestException('Le module Production doit être installé avant Menus.');
    if (!org.menusInstalledAt) throw new BadRequestException('Le module Menus n’est pas installé.');
  }

  async install(organizationId: string, actor: Actor) {
    this.assertManager(actor);
    const org = await this.prisma.organization.findUnique({ where: { id: organizationId }, select: { stocksInstalledAt: true, rnmPricesInstalledAt: true, hrInstalledAt: true, planningInstalledAt: true, technicalSheetsInstalledAt: true, productionInstalledAt: true, menusInstalledAt: true } });
    if (!org?.technicalSheetsInstalledAt || !org.productionInstalledAt) throw new BadRequestException('Installation impossible: Fiches Techniques et Production sont obligatoires.');
    await this.prisma.$transaction(async (tx) => {
      await tx.organization.update({ where: { id: organizationId }, data: { menusInstalledAt: new Date() } });
      for (const name of DEFAULT_DIETS) await tx.menuDiet.upsert({ where: { organizationId_name: { organizationId, name } }, update: {}, create: { organizationId, name } });
      for (const [name, type] of DEFAULT_GUEST_GROUPS) await tx.menuGuestGroup.upsert({ where: { organizationId_name: { organizationId, name } }, update: {}, create: { organizationId, name, type } });
      await tx.auditLog.create({ data: { organizationId, userId: actor.id, action: AuditAction.MODULE_MENUS_INSTALLED, entityType: 'Module', entityId: 'menus', entityName: 'Menus' } });
    });
    return { installed: true, installedApplications: this.installedApps({ ...org, menusInstalledAt: new Date() }) };
  }

  async uninstall(organizationId: string, actor: Actor) {
    this.assertManager(actor);
    const org = await this.prisma.organization.findUnique({ where: { id: organizationId }, select: { stocksInstalledAt: true, rnmPricesInstalledAt: true, hrInstalledAt: true, planningInstalledAt: true, technicalSheetsInstalledAt: true, productionInstalledAt: true } });
    await this.prisma.$transaction(async (tx) => {
      await tx.organization.update({ where: { id: organizationId }, data: { menusInstalledAt: null } });
      await tx.auditLog.create({ data: { organizationId, userId: actor.id, action: AuditAction.MODULE_MENUS_UNINSTALLED, entityType: 'Module', entityId: 'menus', entityName: 'Menus' } });
    });
    return { installed: false, installedApplications: this.installedApps({ ...org, menusInstalledAt: null }) };
  }

  async dashboard(organizationId: string) {
    await this.assertInstalled(organizationId); const today = this.dayRange(); const weekStart = new Date(); weekStart.setDate(weekStart.getDate() - weekStart.getDay() + 1); weekStart.setHours(0,0,0,0); const weekEnd = new Date(weekStart); weekEnd.setDate(weekEnd.getDate() + 7);
    const [activeMenus, weekMenus, cycles, todayMenus] = await Promise.all([
      this.prisma.menu.count({ where: { organizationId, status: { in: ['DRAFT','VALIDATED','PUBLISHED'] } } }),
      this.prisma.menu.findMany({ where: { organizationId, date: { gte: weekStart, lt: weekEnd } }, include: this.menuInclude() }),
      this.prisma.menuCycle.count({ where: { organizationId, status: 'ACTIVE' } }),
      this.prisma.menu.findMany({ where: { organizationId, date: { gte: today.start, lt: today.end } }, include: this.menuInclude() }),
    ]);
    const enriched = weekMenus.map((m) => this.serializeMenu(m));
    const todayEnriched = todayMenus.map((m) => this.serializeMenu(m));
    return { stats: { activeMenus, weekMenus: weekMenus.length, activeCycles: cycles, guestsToday: todayEnriched.reduce((s,m)=>s+m.totalGuests,0), averageCostPerMeal: this.avg(enriched.map(m=>m.costPerGuest)) }, alerts: enriched.flatMap((m) => m.alerts.map((a) => ({ ...a, menuId: m.id, menuName: m.name }))).slice(0, 20), week: enriched, today: todayEnriched };
  }

  async listMenus(organizationId: string, q: any = {}) { await this.assertInstalled(organizationId); const { start, end } = this.dateRange(q); const where: any = { organizationId, status: q.status, service: q.service, siteId: q.siteId, date: start || end ? { gte: start, lt: end } : undefined, OR: q.search ? [{ name: { contains: q.search, mode: 'insensitive' } }, { description: { contains: q.search, mode: 'insensitive' } }] : undefined }; const [items,total] = await Promise.all([this.prisma.menu.findMany({ where, include: this.menuInclude(), orderBy: [{ date: 'asc' }, { service: 'asc' }], ...this.page(q) }), this.prisma.menu.count({ where })]); return { items: items.map((m)=>this.serializeMenu(m)), total, page: q.page ?? 1, pageSize: Math.min(q.pageSize ?? 50, 200) }; }
  async getMenu(organizationId: string, id: string) { await this.assertInstalled(organizationId); const m = await this.prisma.menu.findFirst({ where: { id, organizationId }, include: this.menuInclude(true) }); if (!m) throw new NotFoundException('Menu introuvable'); return this.serializeMenu(m); }
  calendar(organizationId: string, q: any = {}) { return this.listMenus(organizationId, q); }

  async createMenu(organizationId: string, actor: Actor, dto: any) { await this.assertInstalled(organizationId); this.assertWrite(actor); await this.ensureRefs(organizationId, dto); return this.prisma.$transaction(async (tx) => { const menu = await tx.menu.create({ data: { organizationId, name: dto.name, date: new Date(dto.date), service: dto.service, siteId: dto.siteId || null, description: dto.description, expectedGuests: dto.expectedGuests ?? 0, createdById: actor.id } }); if (dto.items?.length) await tx.menuItem.createMany({ data: dto.items.map((i) => ({ organizationId, menuId: menu.id, ...i, portionsOverride: i.portionsOverride == null ? null : new Prisma.Decimal(i.portionsOverride) })) }); await this.history(tx, organizationId, menu.id, null, actor.id, MenuHistoryAction.CREATED, 'Création du menu'); return this.getMenu(organizationId, menu.id); }); }
  async updateMenu(organizationId: string, actor: Actor, id: string, dto: any) { await this.assertInstalled(organizationId); this.assertWrite(actor); const current = await this.ensureMenu(organizationId, id); await this.ensureRefs(organizationId, dto); return this.prisma.$transaction(async (tx) => { await tx.menu.update({ where: { id }, data: { name: dto.name, date: new Date(dto.date), service: dto.service, siteId: dto.siteId || null, description: dto.description, expectedGuests: dto.expectedGuests ?? 0, updatedById: actor.id, productionDirtySince: current.productionGeneratedAt ? new Date() : undefined } }); await tx.menuItem.deleteMany({ where: { menuId: id } }); if (dto.items?.length) await tx.menuItem.createMany({ data: dto.items.map((i) => ({ organizationId, menuId: id, ...i, portionsOverride: i.portionsOverride == null ? null : new Prisma.Decimal(i.portionsOverride) })) }); await this.history(tx, organizationId, id, null, actor.id, MenuHistoryAction.UPDATED, 'Modification du menu'); return this.getMenu(organizationId, id); }); }

  async changeStatus(organizationId: string, actor: Actor, id: string, dto: any) { await this.assertInstalled(organizationId); this.assertManager(actor); return this.prisma.$transaction(async (tx) => { const menu = await tx.menu.findFirst({ where: { id, organizationId }, include: this.menuInclude() }); if (!menu) throw new NotFoundException('Menu introuvable'); if (['VALIDATED','PUBLISHED'].includes(dto.status)) { const alerts = this.serializeMenu(menu).alerts.filter((a) => a.blocking); if (alerts.length) throw new BadRequestException({ message: 'Validation impossible: alertes bloquantes.', alerts }); } const action = dto.status === 'VALIDATED' ? MenuHistoryAction.VALIDATED : dto.status === 'PUBLISHED' ? MenuHistoryAction.PUBLISHED : dto.status === 'ARCHIVED' ? MenuHistoryAction.ARCHIVED : MenuHistoryAction.UPDATED; const serialized = this.serializeMenu(menu); const updated = await tx.menu.update({ where: { id }, data: { status: dto.status, publishedSnapshot: dto.status === 'PUBLISHED' ? serialized : undefined, updatedById: actor.id } }); await this.history(tx, organizationId, id, null, actor.id, action, `Statut ${dto.status}`); return this.getMenu(organizationId, updated.id); }); }

  async diets(organizationId: string) { await this.assertInstalled(organizationId); return this.prisma.menuDiet.findMany({ where: { organizationId }, orderBy: [{ isArchived: 'asc' }, { name: 'asc' }] }); }
  async upsertDiet(organizationId: string, actor: Actor, dto: any, id?: string) { await this.assertInstalled(organizationId); this.assertManager(actor); return id ? this.prisma.menuDiet.update({ where: { id, organizationId }, data: dto }) : this.prisma.menuDiet.create({ data: { organizationId, ...dto } }); }
  async guestGroups(organizationId: string) { await this.assertInstalled(organizationId); return this.prisma.menuGuestGroup.findMany({ where: { organizationId }, orderBy: [{ isArchived: 'asc' }, { name: 'asc' }] }); }
  async upsertGuestGroup(organizationId: string, actor: Actor, dto: any, id?: string) { await this.assertInstalled(organizationId); this.assertManager(actor); return id ? this.prisma.menuGuestGroup.update({ where: { id, organizationId }, data: dto }) : this.prisma.menuGuestGroup.create({ data: { organizationId, ...dto } }); }
  async updateGuests(organizationId: string, actor: Actor, menuId: string, dto: any) { await this.assertInstalled(organizationId); this.assertWrite(actor); await this.ensureMenu(organizationId, menuId); for (const f of dto.forecasts) { await this.ensureGuestGroup(organizationId, f.guestGroupId); if (f.dietId) await this.ensureDiet(organizationId, f.dietId); } return this.prisma.$transaction(async (tx) => { await tx.menuGuestForecast.deleteMany({ where: { menuId } }); if (dto.forecasts.length) await tx.menuGuestForecast.createMany({ data: dto.forecasts.map((f) => ({ organizationId, menuId, ...f })) }); const total = dto.forecasts.reduce((s, f) => s + Number(f.count || 0), 0); await tx.menu.update({ where: { id: menuId }, data: { expectedGuests: total, productionDirtySince: (await tx.menu.findUnique({ where: { id: menuId } })).productionGeneratedAt ? new Date() : undefined } }); await this.history(tx, organizationId, menuId, null, actor.id, MenuHistoryAction.GUESTS_UPDATED, 'Modification des convives', { total }); return this.getMenu(organizationId, menuId); }); }

  async upsertVariant(organizationId: string, actor: Actor, menuId: string, dto: any, id?: string) { await this.assertInstalled(organizationId); this.assertWrite(actor); await this.ensureMenu(organizationId, menuId); await this.ensureDiet(organizationId, dto.dietId); for (const r of dto.replacements ?? []) await this.ensureTechnicalSheet(organizationId, r.replacementTechnicalSheetId); return this.prisma.$transaction(async (tx) => { const variant = id ? await tx.menuVariant.update({ where: { id, organizationId }, data: { dietId: dto.dietId, mode: dto.mode, name: dto.name, expectedGuests: dto.expectedGuests ?? 0, notes: dto.notes } }) : await tx.menuVariant.create({ data: { organizationId, menuId, dietId: dto.dietId, mode: dto.mode, name: dto.name, expectedGuests: dto.expectedGuests ?? 0, notes: dto.notes } }); await tx.menuVariantReplacement.deleteMany({ where: { variantId: variant.id } }); if (dto.replacements?.length) await tx.menuVariantReplacement.createMany({ data: dto.replacements.map((r) => ({ variantId: variant.id, ...r })) }); await tx.menu.update({ where: { id: menuId }, data: { productionDirtySince: (await tx.menu.findUnique({ where: { id: menuId } })).productionGeneratedAt ? new Date() : undefined } }); await this.history(tx, organizationId, menuId, null, actor.id, MenuHistoryAction.VARIANTS_UPDATED, 'Modification des variantes'); return this.getMenu(organizationId, menuId); }); }

  async cycles(organizationId: string, q: any={}) { await this.assertInstalled(organizationId); return this.prisma.menuCycle.findMany({ where: { organizationId, status: q.status }, include: { site: true, items: { include: { technicalSheet: true }, orderBy: [{ weekNumber: 'asc' }, { dayOfWeek: 'asc' }, { service: 'asc' }, { position: 'asc' }] } }, orderBy: { updatedAt: 'desc' }, ...this.page(q) }); }
  async upsertCycle(organizationId: string, actor: Actor, dto: any, id?: string) { await this.assertInstalled(organizationId); this.assertManager(actor); if (dto.siteId) await this.ensureSite(organizationId, dto.siteId); for (const i of dto.items ?? []) await this.ensureTechnicalSheet(organizationId, i.technicalSheetId); return this.prisma.$transaction(async (tx) => { const cycle = id ? await tx.menuCycle.update({ where: { id, organizationId }, data: { name: dto.name, description: dto.description, durationWeeks: dto.durationWeeks, siteId: dto.siteId || null } }) : await tx.menuCycle.create({ data: { organizationId, name: dto.name, description: dto.description, durationWeeks: dto.durationWeeks, siteId: dto.siteId || null } }); await tx.menuCycleItem.deleteMany({ where: { cycleId: cycle.id } }); if (dto.items?.length) await tx.menuCycleItem.createMany({ data: dto.items.map((i) => ({ organizationId, cycleId: cycle.id, ...i })) }); return cycle; }); }
  async replicateCycle(organizationId: string, actor: Actor, cycleId: string, dto: any) { await this.assertInstalled(organizationId); this.assertManager(actor); const cycle = await this.prisma.menuCycle.findFirst({ where: { id: cycleId, organizationId }, include: { items: true } }); if (!cycle) throw new NotFoundException('Cycle introuvable'); const start = new Date(dto.startDate); const end = new Date(dto.endDate); let created = 0; return this.prisma.$transaction(async (tx) => { for (let d = new Date(start); d <= end; d.setDate(d.getDate()+1)) { const diffDays = Math.floor((+d - +start) / 86400000); const weekNumber = (Math.floor(diffDays / 7) % cycle.durationWeeks) + 1; const dayOfWeek = d.getDay() === 0 ? 7 : d.getDay(); const byService = new Map(); for (const item of cycle.items.filter((i) => i.weekNumber === weekNumber && i.dayOfWeek === dayOfWeek)) { const key = item.service; if (!byService.has(key)) byService.set(key, []); byService.get(key).push(item); } for (const [service, items] of byService) { const menu = await tx.menu.create({ data: { organizationId, name: `${cycle.name} - S${weekNumber} J${dayOfWeek} ${service}`, date: new Date(d), service, siteId: dto.siteId || cycle.siteId, expectedGuests: dto.expectedGuests ?? 0, cycleId, cycleWeek: weekNumber, cycleDay: dayOfWeek, createdById: actor.id } }); await tx.menuItem.createMany({ data: items.map((i) => ({ organizationId, menuId: menu.id, section: i.section, technicalSheetId: i.technicalSheetId, position: i.position, notes: i.notes })) }); created++; } } await this.history(tx, organizationId, null, cycleId, actor.id, MenuHistoryAction.CYCLE_REPLICATED, `${created} menus créés depuis le cycle`); return { created }; }); }

  async generateProductions(organizationId: string, actor: Actor, menuId: string, dto: any) { await this.assertInstalled(organizationId); this.assertManager(actor); const menu = await this.prisma.menu.findFirst({ where: { id: menuId, organizationId }, include: this.menuInclude() }); if (!menu) throw new NotFoundException('Menu introuvable'); const serialized = this.serializeMenu(menu); if (!['VALIDATED','PUBLISHED'].includes(menu.status)) throw new BadRequestException('Le menu doit être validé ou publié.'); if (!serialized.totalGuests) throw new BadRequestException('Les convives doivent être renseignés.'); const blocking = serialized.alerts.filter((a) => a.blocking); if (blocking.length) throw new BadRequestException({ message: 'Génération impossible: alertes bloquantes.', alerts: blocking }); if (menu.productionGeneratedAt && !dto.force) throw new BadRequestException('Productions déjà générées: confirmation force requise.'); const effective = this.effectiveProductionLines(menu); return this.prisma.$transaction(async (tx) => { const created = []; const groups = dto.mode === MenuProductionGenerationMode.DETAILED ? effective.map((l) => [l.technicalSheetId, [l]]) : [...effective.reduce((m,l)=>m.set(l.technicalSheetId,[...(m.get(l.technicalSheetId)||[]),l]), new Map()).entries()]; for (const [technicalSheetId, lines] of groups) { const sheet = lines[0].technicalSheet; const portions = lines.reduce((s,l)=>s + l.portions, 0); const number = await this.nextProductionNumber(tx, organizationId); const order = await tx.productionOrder.create({ data: { organizationId, number, name: dto.mode === 'GROUPED' ? `Menu ${menu.name} - ${sheet.name}` : sheet.name, technicalSheetId, productionDate: menu.date, plannedTime: dto.plannedTime || '08:00', plannedPortions: new Prisma.Decimal(portions), priority: ProductionPriority.NORMAL, comments: `Généré depuis Menus: ${menu.name}`, source: 'MENUS', createdById: actor.id } }); await this.recalculateProductionOrderTx(tx, organizationId, order.id); await tx.menuProductionLink.create({ data: { organizationId, menuId, productionOrderId: order.id, generationMode: dto.mode, snapshot: { menuId, lines: lines.map((l)=>({ section: l.section, variantId: l.variantId, portions: l.portions })) } } }); created.push(order); } await tx.menu.update({ where: { id: menuId }, data: { productionGeneratedAt: new Date(), productionDirtySince: null } }); await this.history(tx, organizationId, menuId, null, actor.id, MenuHistoryAction.PRODUCTION_GENERATED, `${created.length} ordres de production générés`, { mode: dto.mode }); return { created: created.length, orders: created }; }); }

  async exports(organizationId: string, q: any = {}) { await this.assertInstalled(organizationId); return this.prisma.menuExport.findMany({ where: { organizationId, menuId: q.menuId }, include: { requestedBy: { select: { email: true, firstName: true, lastName: true } }, menu: true }, orderBy: { createdAt: 'desc' }, ...this.page(q) }); }
  async prepareExport(organizationId: string, actor: Actor, dto: any) { await this.assertInstalled(organizationId); this.assertManager(actor); const menus = dto.menuId ? [await this.getMenu(organizationId, dto.menuId)] : (await this.listMenus(organizationId, { startDate: dto.startDate, endDate: dto.endDate, pageSize: 200 })).items; const snapshot = { generatedAt: new Date().toISOString(), audience: dto.audience, menus }; const ext = dto.format === MenuExportFormat.EXCEL ? 'xlsx' : dto.format === MenuExportFormat.PDF ? 'pdf' : 'print'; const exp = await this.prisma.menuExport.create({ data: { organizationId, menuId: dto.menuId || null, requestedById: actor.id, format: dto.format, audience: dto.audience, filename: `menus-${dto.audience.toLowerCase()}-${Date.now()}.${ext}`, filters: dto.filters, snapshot } }); await this.prisma.menuHistory.create({ data: { organizationId, menuId: dto.menuId || null, actorUserId: actor.id, action: MenuHistoryAction.EXPORT_GENERATED, summary: `Export ${dto.audience} ${dto.format}`, details: { exportId: exp.id } } }); return exp; }
  async historyList(organizationId: string, q: any = {}) { await this.assertInstalled(organizationId); return this.prisma.menuHistory.findMany({ where: { organizationId, menuId: q.menuId, cycleId: q.cycleId, action: q.action }, include: { actorUser: { select: { email: true, firstName: true, lastName: true } }, menu: true, cycle: true }, orderBy: { createdAt: 'desc' }, ...this.page(q) }); }

  private menuInclude(full=false) { return { site: true, cycle: true, items: { include: { technicalSheet: { include: this.sheetInclude() } }, orderBy: [{ section: 'asc' }, { position: 'asc' }] }, variants: { include: { diet: true, replacements: { include: { menuItem: true, replacementTechnicalSheet: { include: this.sheetInclude() } } } } }, guestForecasts: { include: { guestGroup: true, diet: true } }, productionLinks: { include: { productionOrder: true } }, ...(full ? { exports: { orderBy: { createdAt: 'desc' }, take: 20 }, history: { orderBy: { createdAt: 'desc' }, take: 50, include: { actorUser: { select: { email: true, firstName: true, lastName: true } } } } } : {}) }; }
  private sheetInclude() { return { ingredients: { include: { allergens: { include: { allergen: true } } } } }; }
  private serializeMenu(m: any) { const totalGuests = (m.guestForecasts?.length ? m.guestForecasts.reduce((s,f)=>s+f.count,0) : m.expectedGuests) || 0; const sheets = (m.items ?? []).map((i)=>i.technicalSheet).filter(Boolean); const allergens = [...new Set(sheets.flatMap((s)=>s.ingredients?.flatMap((i)=>i.allergens?.map((a)=>a.allergen?.name).filter(Boolean) ?? []) ?? []))]; const estimatedCost = (m.items ?? []).reduce((sum,i)=> sum + Number(i.technicalSheet?.costPerPortion ?? 0) * Number(i.portionsOverride ?? totalGuests), 0); const alerts = []; if (!(m.items?.length)) alerts.push({ code: 'INCOMPLETE_MENU', severity: 'WARNING', title: 'Menu sans composition', blocking: true }); if (!totalGuests) alerts.push({ code: 'NO_GUESTS', severity: 'WARNING', title: 'Convives non renseignés', blocking: false }); if ((m.items ?? []).some((i)=>!['ACTIVE','VALIDATED'].includes(i.technicalSheet?.status) || i.technicalSheet?.isArchived)) alerts.push({ code: 'TECHNICAL_SHEET_INACTIVE', severity: 'CRITICAL', title: 'Fiche technique manquante ou archivée', blocking: true }); if (allergens.length) alerts.push({ code: 'ALLERGENS', severity: 'INFO', title: 'Allergènes présents', blocking: false, allergens }); if (['VALIDATED','PUBLISHED'].includes(m.status) && !m.productionGeneratedAt) alerts.push({ code: 'PRODUCTION_NOT_GENERATED', severity: 'WARNING', title: 'Production non générée', blocking: false }); if (m.productionDirtySince) alerts.push({ code: 'PRODUCTION_DIRTY', severity: 'WARNING', title: 'Menu modifié après génération Production', blocking: false }); return { ...m, totalGuests, estimatedCost, costPerGuest: totalGuests ? estimatedCost / totalGuests : 0, allergens, alerts }; }
  private effectiveProductionLines(menu: any) { const totalGuests = menu.guestForecasts?.reduce((s,f)=>s+f.count,0) || menu.expectedGuests || 0; return (menu.items ?? []).map((i)=>({ technicalSheetId: i.technicalSheetId, technicalSheet: i.technicalSheet, section: i.section, portions: Number(i.portionsOverride ?? totalGuests) })); }
  private avg(v: number[]) { const f = v.filter(Number.isFinite); return f.length ? f.reduce((a,b)=>a+b,0)/f.length : 0; }
  private async ensureRefs(org: string, dto: any) { if (dto.siteId) await this.ensureSite(org, dto.siteId); for (const i of dto.items ?? []) await this.ensureTechnicalSheet(org, i.technicalSheetId); }
  private async ensureMenu(org: string, id: string) { const x = await this.prisma.menu.findFirst({ where: { id, organizationId: org } }); if (!x) throw new NotFoundException('Menu introuvable'); return x; }
  private async ensureSite(org: string, id: string) { const x = await this.prisma.site.findFirst({ where: { id, organizationId: org, isArchived: false } }); if (!x) throw new NotFoundException('Site introuvable'); return x; }
  private async ensureDiet(org: string, id: string) { const x = await this.prisma.menuDiet.findFirst({ where: { id, organizationId: org, isArchived: false } }); if (!x) throw new NotFoundException('Régime introuvable'); return x; }
  private async ensureGuestGroup(org: string, id: string) { const x = await this.prisma.menuGuestGroup.findFirst({ where: { id, organizationId: org, isArchived: false } }); if (!x) throw new NotFoundException('Groupe de convives introuvable'); return x; }
  private async ensureTechnicalSheet(org: string, id: string) { const x = await this.prisma.technicalSheet.findFirst({ where: { id, organizationId: org, isArchived: false, status: { in: ['ACTIVE','VALIDATED'] } } }); if (!x) throw new NotFoundException('Fiche technique active introuvable'); return x; }
  private async recalculateProductionOrderTx(tx: any, organizationId: string, orderId: string) { const order = await tx.productionOrder.findFirst({ where: { id: orderId, organizationId }, include: { technicalSheet: { include: { ingredients: { include: { product: { include: { unit: true, primarySupplier: true, stocks: true } }, unit: true } } } } } }); if (!order) return; await tx.productionMaterialRequirement.deleteMany({ where: { orderId } }); const factor = new Prisma.Decimal(order.plannedPortions).div(order.technicalSheet.referencePortions || 1); let estimatedCost = new Prisma.Decimal(0); for (const ing of order.technicalSheet.ingredients) { const required = new Prisma.Decimal(ing.quantity).mul(factor); const available = ing.product.stocks.reduce((s, st) => s.add(st.quantity), new Prisma.Decimal(0)); const status = ing.product.isArchived ? ProductionMaterialStatus.PRODUCT_ARCHIVED : available.isZero() ? ProductionMaterialStatus.STOCK_UNKNOWN : available.lt(required) ? ProductionMaterialStatus.INSUFFICIENT_STOCK : available.sub(required).lte(ing.product.minimumStock) ? ProductionMaterialStatus.POTENTIAL_SHORTAGE : ProductionMaterialStatus.OK; const cost = ing.cost == null ? null : new Prisma.Decimal(ing.cost).mul(factor); if (cost) estimatedCost = estimatedCost.add(cost); await tx.productionMaterialRequirement.create({ data: { organizationId, orderId, technicalSheetIngredientId: ing.id, productId: ing.productId, unitId: ing.unitId, supplierId: ing.product.primarySupplierId, requiredQuantity: required, stockAvailable: available, varianceQuantity: available.sub(required), status, estimatedCost: cost, productNameSnapshot: ing.product.name, unitSymbolSnapshot: ing.unit.symbol, supplierNameSnapshot: ing.product.primarySupplier?.name, details: { source: 'MENUS', sourceMenuOrderId: orderId } } }); } await tx.productionOrder.update({ where: { id: orderId }, data: { estimatedCost } }); }
  private async nextProductionNumber(tx: any, org: string) { const year = new Date().getFullYear(); const count = await tx.productionOrder.count({ where: { organizationId: org, number: { startsWith: `OP-${year}-` } } }); return `OP-${year}-${String(count + 1).padStart(4, '0')}`; }
  private history(tx: any, organizationId: string, menuId: string | null, cycleId: string | null, actorUserId: string | null, action: any, summary: string, details?: any) { return tx.menuHistory.create({ data: { organizationId, menuId, cycleId, actorUserId, action, summary, details } }); }
  private installedApps(org: any) { return [...(org?.stocksInstalledAt ? ['stocks'] : []), ...(org?.rnmPricesInstalledAt ? ['rnm-prices'] : []), ...(org?.hrInstalledAt ? ['hr'] : []), ...(org?.planningInstalledAt ? ['planning'] : []), ...(org?.technicalSheetsInstalledAt ? ['technical-sheets'] : []), ...(org?.productionInstalledAt ? ['production'] : []), ...(org?.menusInstalledAt ? ['menus'] : [])]; }
}
