import { HrEntitlementAccrualFrequency, PlanningTimeUnit } from '@prisma/client';

export type HrCountryCode = 'FR' | 'FI';
export type PlanningEmploymentFramework = 'PRIVATE' | 'PUBLIC' | 'MIXED' | 'LOCAL' | 'CUSTOM';
export type PlanningOrganizationTypeCode = 'RESTAURANT' | 'CENTRAL_KITCHEN' | 'COLLECTIVE_CATERING' | 'ADMINISTRATION' | 'BAKERY' | 'CAFE' | 'OTHER';
export type HrEntitlementCategory = 'LEAVE' | 'WORKING_TIME' | 'ABSENCE' | 'RECOVERY' | 'SENIORITY' | 'HEALTH' | 'LOCAL' | 'SAVINGS';

export type HrEntitlementCatalogTemplate = {
  countryCode: HrCountryCode;
  employmentFramework: PlanningEmploymentFramework;
  organizationType?: PlanningOrganizationTypeCode | 'ALL';
  code: string;
  label: string;
  shortDescription: string;
  longDescription: string;
  category: HrEntitlementCategory;
  examples: string[];
  accountType: string;
  unit: PlanningTimeUnit;
  defaultAccrualFrequency: HrEntitlementAccrualFrequency;
  defaultAccrualQuantity?: number;
  defaultStartCondition?: string;
  startsAfterTrialPeriod?: boolean;
  minimumSeniorityMonths?: number;
  prorateByContractTime?: boolean;
  maxBalance?: number;
  carryOverEnabled?: boolean;
  requiresAdminValidation?: boolean;
  enabledByDefault?: boolean;
  isRecommended?: boolean;
  isCommon?: boolean;
  isAdvanced?: boolean;
  displayOrder: number;
  recommendedFor?: string[];
  sourceLabel?: string;
  sourceUrl?: string;
  sourceReference?: string;
};

const CENTRAL_OR_PUBLIC_TYPES = ['cuisine centrale', 'collectivite', 'collectivité', 'restauration collective', 'administration', 'public'];
const SMALL_FOOD_TYPES = ['restaurant', 'cafe', 'café', 'boulangerie', 'traiteur'];

export const HR_ENTITLEMENT_CATALOG: HrEntitlementCatalogTemplate[] = [
  {
    countryCode: 'FR',
    employmentFramework: 'PRIVATE',
    organizationType: 'ALL',
    code: 'paid_leave',
    label: 'Congés payés',
    shortDescription: 'Droit de congés rémunérés du secteur privé.',
    longDescription: 'Modèle d’aide à la configuration des congés payés. La règle proposée peut être ajustée selon convention, statut et accords internes.',
    category: 'LEAVE',
    examples: ['Acquisition mensuelle', 'Solde d’ouverture', 'Consommation via absence ou planning'],
    accountType: 'paid_leave',
    unit: PlanningTimeUnit.DAYS,
    defaultAccrualFrequency: HrEntitlementAccrualFrequency.MONTHLY,
    defaultAccrualQuantity: 2.5,
    defaultStartCondition: 'Après ouverture du droit selon règles internes',
    startsAfterTrialPeriod: true,
    prorateByContractTime: true,
    carryOverEnabled: true,
    enabledByDefault: true,
    isRecommended: true,
    isCommon: true,
    displayOrder: 10,
    recommendedFor: SMALL_FOOD_TYPES,
    sourceLabel: 'Modèle France privé',
    sourceReference: 'À valider selon convention et accords internes',
  },
  {
    countryCode: 'FR',
    employmentFramework: 'PUBLIC',
    organizationType: 'ALL',
    code: 'annual_leave_public',
    label: 'Congés annuels',
    shortDescription: 'Congés annuels adaptés aux cadres publics ou collectivités.',
    longDescription: 'Modèle pour organisations publiques ou assimilées. La logique de référence peut être fondée sur le rythme hebdomadaire travaillé et reste à valider selon votre cadre exact.',
    category: 'LEAVE',
    examples: ['Base annuelle', 'Ex. 5 fois le nombre de jours travaillés par semaine', 'Solde d’ouverture manuel'],
    accountType: 'annual_leave',
    unit: PlanningTimeUnit.DAYS,
    defaultAccrualFrequency: HrEntitlementAccrualFrequency.YEARLY,
    defaultStartCondition: 'Crédit annuel ou solde d’ouverture',
    carryOverEnabled: true,
    enabledByDefault: true,
    isRecommended: true,
    isCommon: true,
    displayOrder: 12,
    recommendedFor: CENTRAL_OR_PUBLIC_TYPES,
    sourceLabel: 'Modèle France fonction publique',
    sourceReference: 'À valider selon statut, collectivité et accords applicables',
  },
  {
    countryCode: 'FR',
    employmentFramework: 'PUBLIC',
    organizationType: 'ALL',
    code: 'statutory_leave',
    label: 'Congés statutaires',
    shortDescription: 'Droit statutaire distinct des congés annuels.',
    longDescription: 'Modèle pour suivre un droit statutaire séparé lorsque l’organisation le distingue dans ses documents ou accords.',
    category: 'LEAVE',
    examples: ['Congés statutaires ODS', 'Solde dédié', 'Consommation séparée'],
    accountType: 'statutory_leave',
    unit: PlanningTimeUnit.DAYS,
    defaultAccrualFrequency: HrEntitlementAccrualFrequency.YEARLY,
    defaultStartCondition: 'Selon statut ou accord',
    carryOverEnabled: true,
    isRecommended: true,
    isCommon: false,
    displayOrder: 14,
    recommendedFor: CENTRAL_OR_PUBLIC_TYPES,
    sourceLabel: 'Modèle France public',
  },
  {
    countryCode: 'FR',
    employmentFramework: 'MIXED',
    organizationType: 'ALL',
    code: 'sick_leave',
    label: 'Absence maladie',
    shortDescription: 'Absence maladie suivie sans mélanger les congés.',
    longDescription: 'Permet de suivre les absences maladie dans le planning et les compteurs, selon validation et règles internes.',
    category: 'ABSENCE',
    examples: ['Absence approuvée', 'Statut de jour', 'Impact compteur à paramétrer'],
    accountType: 'sick_leave',
    unit: PlanningTimeUnit.DAYS,
    defaultAccrualFrequency: HrEntitlementAccrualFrequency.MANUAL,
    enabledByDefault: true,
    isRecommended: true,
    isCommon: true,
    displayOrder: 20,
    sourceLabel: 'Modèle absence',
  },
  {
    countryCode: 'FR',
    employmentFramework: 'PRIVATE',
    organizationType: 'ALL',
    code: 'overtime',
    label: 'Heures supplémentaires',
    shortDescription: 'Suivi des heures supplémentaires validées.',
    longDescription: 'Compteur événementiel alimenté plus tard par validation manager, émargement ou ajustement.',
    category: 'WORKING_TIME',
    examples: ['Écart validé', 'Crédit récupération', 'Export paie futur'],
    accountType: 'overtime',
    unit: PlanningTimeUnit.MINUTES,
    defaultAccrualFrequency: HrEntitlementAccrualFrequency.EVENT_BASED,
    isRecommended: true,
    isCommon: true,
    displayOrder: 30,
    sourceLabel: 'Modèle temps de travail',
  },
  {
    countryCode: 'FR',
    employmentFramework: 'MIXED',
    organizationType: 'ALL',
    code: 'recovery',
    label: 'Récupération',
    shortDescription: 'Compensation d’heures ou d’écarts validés.',
    longDescription: 'Compteur séparé pour les heures de récupération, utile en cuisine centrale, collectivité ou organisation annualisée.',
    category: 'RECOVERY',
    examples: ['Heures récupérées', 'Solde en heures', 'Consommation via planning'],
    accountType: 'recovery',
    unit: PlanningTimeUnit.MINUTES,
    defaultAccrualFrequency: HrEntitlementAccrualFrequency.EVENT_BASED,
    defaultStartCondition: 'Après validation manager',
    carryOverEnabled: true,
    isRecommended: true,
    isCommon: true,
    displayOrder: 40,
    recommendedFor: CENTRAL_OR_PUBLIC_TYPES,
    sourceLabel: 'Modèle récupération',
  },
  {
    countryCode: 'FR',
    employmentFramework: 'PUBLIC',
    organizationType: 'ALL',
    code: 'rtt',
    label: 'RTT',
    shortDescription: 'Repos lié au temps de travail ou à l’organisation annuelle.',
    longDescription: 'Droit optionnel à activer seulement si votre organisation dispose de RTT. Il doit rester séparé des congés annuels ou payés.',
    category: 'WORKING_TIME',
    examples: ['RTT libres', 'Crédit annuel', 'Solde distinct des congés'],
    accountType: 'rtt',
    unit: PlanningTimeUnit.DAYS,
    defaultAccrualFrequency: HrEntitlementAccrualFrequency.YEARLY,
    defaultStartCondition: 'Selon profil ou accord',
    prorateByContractTime: true,
    carryOverEnabled: true,
    isRecommended: true,
    isCommon: false,
    displayOrder: 50,
    recommendedFor: CENTRAL_OR_PUBLIC_TYPES,
    sourceLabel: 'Modèle RTT',
  },
  {
    countryCode: 'FR',
    employmentFramework: 'MIXED',
    organizationType: 'ALL',
    code: 'time_savings_account',
    label: 'CET',
    shortDescription: 'Compte épargne temps.',
    longDescription: 'Droit avancé pour stocker des jours ou heures selon règles applicables. À activer seulement si l’organisation l’utilise.',
    category: 'SAVINGS',
    examples: ['Stockage de jours', 'Report encadré', 'Usage futur paie/export'],
    accountType: 'cet',
    unit: PlanningTimeUnit.DAYS,
    defaultAccrualFrequency: HrEntitlementAccrualFrequency.MANUAL,
    carryOverEnabled: true,
    isAdvanced: true,
    displayOrder: 60,
    sourceLabel: 'Modèle CET',
  },
  {
    countryCode: 'FR',
    employmentFramework: 'MIXED',
    organizationType: 'ALL',
    code: 'split_leave',
    label: 'Fractionnement',
    shortDescription: 'Droit de fractionnement si applicable.',
    longDescription: 'Droit spécifique à suivre séparément des congés principaux lorsque vos règles le prévoient.',
    category: 'LEAVE',
    examples: ['Congés fractionnement', 'Crédit séparé', 'À vérifier selon accord'],
    accountType: 'split_leave',
    unit: PlanningTimeUnit.DAYS,
    defaultAccrualFrequency: HrEntitlementAccrualFrequency.YEARLY,
    isAdvanced: true,
    displayOrder: 70,
    sourceLabel: 'Modèle fractionnement',
  },
  {
    countryCode: 'FR',
    employmentFramework: 'MIXED',
    organizationType: 'ALL',
    code: 'seniority_leave',
    label: 'Congé d’ancienneté',
    shortDescription: 'Droit supplémentaire selon ancienneté.',
    longDescription: 'Droit optionnel lié à l’ancienneté. Pour un collaborateur déjà ancien, privilégier un solde d’ouverture plutôt qu’un recalcul historique complet.',
    category: 'SENIORITY',
    examples: ['Après X années', 'Solde d’ouverture', 'Ajustement manuel'],
    accountType: 'seniority_leave',
    unit: PlanningTimeUnit.DAYS,
    defaultAccrualFrequency: HrEntitlementAccrualFrequency.YEARLY,
    minimumSeniorityMonths: 12,
    isAdvanced: true,
    displayOrder: 80,
    sourceLabel: 'Modèle ancienneté',
  },
  {
    countryCode: 'FR',
    employmentFramework: 'PUBLIC',
    organizationType: 'ALL',
    code: 'special_leave_authorization',
    label: 'Autorisations spéciales d’absence',
    shortDescription: 'Absences autorisées spécifiques.',
    longDescription: 'Modèle pour suivre séparément les autorisations spéciales d’absence, sans les mélanger aux congés annuels.',
    category: 'ABSENCE',
    examples: ['Absence autorisée', 'ASA', 'Validation interne'],
    accountType: 'special_leave_authorization',
    unit: PlanningTimeUnit.DAYS,
    defaultAccrualFrequency: HrEntitlementAccrualFrequency.MANUAL,
    isAdvanced: true,
    displayOrder: 90,
    recommendedFor: CENTRAL_OR_PUBLIC_TYPES,
    sourceLabel: 'Modèle absence publique',
  },
  {
    countryCode: 'FR',
    employmentFramework: 'MIXED',
    organizationType: 'ALL',
    code: 'union_leave',
    label: 'Congé syndical',
    shortDescription: 'Absence syndicale si applicable.',
    longDescription: 'Droit ou absence spécifique à activer uniquement si l’organisation le suit.',
    category: 'ABSENCE',
    examples: ['Congé syndical', 'Autorisation dédiée', 'Validation admin'],
    accountType: 'union_leave',
    unit: PlanningTimeUnit.DAYS,
    defaultAccrualFrequency: HrEntitlementAccrualFrequency.MANUAL,
    isAdvanced: true,
    displayOrder: 100,
    sourceLabel: 'Modèle congé syndical',
  },
  {
    countryCode: 'FR',
    employmentFramework: 'MIXED',
    organizationType: 'ALL',
    code: 'rqth_accommodation',
    label: 'RQTH / aménagement',
    shortDescription: 'Suivi indicatif d’un aménagement ou droit associé.',
    longDescription: 'Modèle de suivi interne, à utiliser avec prudence selon politique RH et confidentialité. Ne remplace pas le dossier RH officiel.',
    category: 'HEALTH',
    examples: ['Aménagement à vérifier', 'Suivi indicatif', 'Données sensibles à limiter'],
    accountType: 'rqth_accommodation',
    unit: PlanningTimeUnit.DAYS,
    defaultAccrualFrequency: HrEntitlementAccrualFrequency.MANUAL,
    requiresAdminValidation: true,
    isAdvanced: true,
    displayOrder: 110,
    sourceLabel: 'Modèle RQTH interne',
  },
  {
    countryCode: 'FR',
    employmentFramework: 'LOCAL',
    organizationType: 'ALL',
    code: 'green_hours',
    label: 'Heures vertes',
    shortDescription: 'Compte local personnalisable.',
    longDescription: 'Droit local ou interne configurable lorsque votre organisation suit des heures spécifiques.',
    category: 'LOCAL',
    examples: ['Crédit d’heures interne', 'Selon ancienneté', 'Règle locale'],
    accountType: 'green_hours',
    unit: PlanningTimeUnit.MINUTES,
    defaultAccrualFrequency: HrEntitlementAccrualFrequency.YEARLY,
    isAdvanced: true,
    displayOrder: 120,
    recommendedFor: CENTRAL_OR_PUBLIC_TYPES,
    sourceLabel: 'Modèle local',
  },
  {
    countryCode: 'FR',
    employmentFramework: 'MIXED',
    organizationType: 'ALL',
    code: 'training',
    label: 'Formation',
    shortDescription: 'Temps de formation suivi séparément.',
    longDescription: 'Permet de suivre la formation comme absence ou statut métier sans l’écraser dans un compteur de congés.',
    category: 'ABSENCE',
    examples: ['Formation obligatoire', 'Statut journée', 'Export futur'],
    accountType: 'training',
    unit: PlanningTimeUnit.DAYS,
    defaultAccrualFrequency: HrEntitlementAccrualFrequency.MANUAL,
    isRecommended: true,
    isCommon: true,
    displayOrder: 130,
    recommendedFor: CENTRAL_OR_PUBLIC_TYPES,
    sourceLabel: 'Modèle formation',
  },
  {
    countryCode: 'FI',
    employmentFramework: 'MIXED',
    organizationType: 'ALL',
    code: 'annual_leave',
    label: 'Congés annuels',
    shortDescription: 'Congés annuels du cadre Finlande.',
    longDescription: 'Modèle Finlande à valider selon convention et règles internes, avec acquisition pouvant dépendre de l’ancienneté et du régime de travail.',
    category: 'LEAVE',
    examples: ['2 ou 2,5 jours selon ancienneté', 'Solde d’ouverture', 'Convention applicable'],
    accountType: 'annual_leave',
    unit: PlanningTimeUnit.DAYS,
    defaultAccrualFrequency: HrEntitlementAccrualFrequency.MONTHLY,
    defaultAccrualQuantity: 2,
    prorateByContractTime: true,
    carryOverEnabled: true,
    enabledByDefault: true,
    isRecommended: true,
    isCommon: true,
    displayOrder: 10,
    sourceLabel: 'Modèle Finlande',
    sourceReference: 'À valider selon convention et règles internes',
  },
  {
    countryCode: 'FI',
    employmentFramework: 'MIXED',
    organizationType: 'ALL',
    code: 'annual_leave_14_days',
    label: 'Règle 14 jours',
    shortDescription: 'Mode d’acquisition Finlande selon jours travaillés.',
    longDescription: 'Modèle avancé pour les organisations qui appliquent un seuil fondé sur les jours travaillés.',
    category: 'LEAVE',
    examples: ['14 jours travaillés', 'Acquisition mensuelle', 'À valider'],
    accountType: 'annual_leave_14_days',
    unit: PlanningTimeUnit.DAYS,
    defaultAccrualFrequency: HrEntitlementAccrualFrequency.MONTHLY,
    defaultAccrualQuantity: 2,
    prorateByContractTime: true,
    isAdvanced: true,
    displayOrder: 20,
    sourceLabel: 'Modèle Finlande',
  },
  {
    countryCode: 'FI',
    employmentFramework: 'MIXED',
    organizationType: 'ALL',
    code: 'annual_leave_35_hours',
    label: 'Règle 35 heures',
    shortDescription: 'Mode d’acquisition Finlande selon heures travaillées.',
    longDescription: 'Modèle avancé pour les organisations qui appliquent un seuil fondé sur les heures travaillées.',
    category: 'LEAVE',
    examples: ['35 heures travaillées', 'Acquisition mensuelle', 'À valider'],
    accountType: 'annual_leave_35_hours',
    unit: PlanningTimeUnit.DAYS,
    defaultAccrualFrequency: HrEntitlementAccrualFrequency.MONTHLY,
    defaultAccrualQuantity: 2,
    prorateByContractTime: true,
    isAdvanced: true,
    displayOrder: 30,
    sourceLabel: 'Modèle Finlande',
  },
  {
    countryCode: 'FI',
    employmentFramework: 'MIXED',
    organizationType: 'ALL',
    code: 'holiday_compensation',
    label: 'Compensation de congés',
    shortDescription: 'Compensation liée aux congés si applicable.',
    longDescription: 'Modèle Finlande optionnel pour suivre séparément une compensation de congés.',
    category: 'LEAVE',
    examples: ['Compensation', 'Solde distinct', 'À valider'],
    accountType: 'holiday_compensation',
    unit: PlanningTimeUnit.DAYS,
    defaultAccrualFrequency: HrEntitlementAccrualFrequency.MANUAL,
    isAdvanced: true,
    displayOrder: 40,
    sourceLabel: 'Modèle Finlande',
  },
  {
    countryCode: 'FI',
    employmentFramework: 'MIXED',
    organizationType: 'ALL',
    code: 'sick_leave',
    label: 'Maladie',
    shortDescription: 'Absence maladie suivie dans le planning.',
    longDescription: 'Absence maladie suivie sans la fusionner avec les congés annuels.',
    category: 'ABSENCE',
    examples: ['Absence approuvée', 'Statut journée', 'Validation interne'],
    accountType: 'sick_leave',
    unit: PlanningTimeUnit.DAYS,
    defaultAccrualFrequency: HrEntitlementAccrualFrequency.MANUAL,
    enabledByDefault: true,
    isRecommended: true,
    isCommon: true,
    displayOrder: 50,
    sourceLabel: 'Modèle Finlande',
  },
  {
    countryCode: 'FI',
    employmentFramework: 'MIXED',
    organizationType: 'ALL',
    code: 'working_time',
    label: 'Temps de travail',
    shortDescription: 'Suivi du temps de travail planifié et validé.',
    longDescription: 'Compteur de temps qui pourra être alimenté par planning, émargement et validation.',
    category: 'WORKING_TIME',
    examples: ['Heures planifiées', 'Émargement futur', 'Écarts validés'],
    accountType: 'working_time',
    unit: PlanningTimeUnit.MINUTES,
    defaultAccrualFrequency: HrEntitlementAccrualFrequency.EVENT_BASED,
    enabledByDefault: true,
    isRecommended: true,
    isCommon: true,
    displayOrder: 60,
    sourceLabel: 'Modèle Finlande',
  },
  {
    countryCode: 'FI',
    employmentFramework: 'MIXED',
    organizationType: 'ALL',
    code: 'compensation',
    label: 'Compensation / récupération',
    shortDescription: 'Compensation d’heures selon paramétrage.',
    longDescription: 'Compteur local de compensation ou récupération selon règles internes et conventions applicables.',
    category: 'RECOVERY',
    examples: ['Écart validé', 'Compensation', 'Récupération'],
    accountType: 'compensation',
    unit: PlanningTimeUnit.MINUTES,
    defaultAccrualFrequency: HrEntitlementAccrualFrequency.EVENT_BASED,
    isRecommended: true,
    isCommon: true,
    displayOrder: 70,
    recommendedFor: CENTRAL_OR_PUBLIC_TYPES,
    sourceLabel: 'Modèle Finlande',
  },
  {
    countryCode: 'FI',
    employmentFramework: 'MIXED',
    organizationType: 'ALL',
    code: 'seniority_leave',
    label: 'Droit selon ancienneté',
    shortDescription: 'Droit ou taux ajusté selon ancienneté.',
    longDescription: 'Modèle pour suivre une règle d’ancienneté ou un seuil à partir duquel l’acquisition change.',
    category: 'SENIORITY',
    examples: ['2,5 jours selon ancienneté', 'Solde manuel', 'Date d’effet'],
    accountType: 'seniority_leave',
    unit: PlanningTimeUnit.DAYS,
    defaultAccrualFrequency: HrEntitlementAccrualFrequency.YEARLY,
    minimumSeniorityMonths: 12,
    isAdvanced: true,
    displayOrder: 80,
    sourceLabel: 'Modèle Finlande',
  },
  {
    countryCode: 'FI',
    employmentFramework: 'LOCAL',
    organizationType: 'ALL',
    code: 'local_agreement_right',
    label: 'Droit conventionnel ou local',
    shortDescription: 'Droit propre à votre convention ou organisation.',
    longDescription: 'Modèle personnalisable pour les règles propres à l’organisation.',
    category: 'LOCAL',
    examples: ['Accord local', 'Convention', 'Règle interne'],
    accountType: 'local_right',
    unit: PlanningTimeUnit.DAYS,
    defaultAccrualFrequency: HrEntitlementAccrualFrequency.MANUAL,
    isAdvanced: true,
    displayOrder: 90,
    sourceLabel: 'Modèle local',
  },
];

export function templatesForCountry(countryCode: HrCountryCode) {
  return HR_ENTITLEMENT_CATALOG.filter(item => item.countryCode === countryCode);
}

export function isTemplateRecommendedFor(template: HrEntitlementCatalogTemplate, organizationType?: string | null, employmentFramework?: string | null) {
  if (template.enabledByDefault || template.isRecommended) return true;
  if (employmentFramework && template.employmentFramework === employmentFramework && template.isCommon) return true;
  if (!template.recommendedFor?.length || !organizationType) return false;
  const normalized = normalize(organizationType);
  return template.recommendedFor.some(value => normalized.includes(normalize(value)));
}

export function frameworkMatches(template: HrEntitlementCatalogTemplate, employmentFramework?: string | null) {
  if (!employmentFramework) return true;
  return template.employmentFramework === employmentFramework || template.employmentFramework === 'MIXED' || template.employmentFramework === 'LOCAL';
}

function normalize(value: string) {
  return value.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '');
}
